const STATEMENTS = [
  "Hunde sind besser als Katzen.",
  "Ananas gehört auf Pizza.",
  "Kaffee schmeckt besser als Tee.",
  "Serien sind besser als Filme.",
  "Man sollte Ketchup und Mayo zu Pommes mischen.",
  "Sommer ist die beste Jahreszeit.",
  "Man sollte nie am Handy sein, wenn man mit Freunden isst.",
  "Montage sind gar nicht so schlimm.",
  "Das Toilettenpapier sollte immer 'über' hängen, nicht 'unter'.",
  "Horrorfilme sind überbewertet.",
  "Socken mit Sandalen sind ein No-Go.",
  "Frühaufsteher sind produktiver als Nachteulen.",
  "Man sollte im Restaurant immer Trinkgeld geben, auch bei schlechtem Service.",
  "Cornflakes mit warmer Milch schmecken besser.",
  "Man sollte sich Handynummern merken können, statt sie zu speichern.",
  "Es ist ok, den letzten Bissen vom Teller des Partners zu essen, ohne zu fragen.",
  "Geld ist wichtiger als Liebe.",
  "Man sollte nie mit dem Ex befreundet bleiben.",
  "Eine große Altersdifferenz in einer Beziehung ist kein Problem.",
  "Man sollte niemals eine Fernbeziehung führen.",
  "Wer zuerst von Liebe spricht, hat die Beziehung verloren.",
  "Online-Dating ist besser als sich im echten Leben kennenzulernen.",
  "Eifersucht ist ein Zeichen von echter Liebe.",
  "Man sollte das Handy des Partners jederzeit durchsuchen dürfen.",
  "Heiraten ist heutzutage überflüssig.",
  "Eine Beziehung ohne gemeinsame Finanzen funktioniert nicht.",
  "Man sollte niemals mit dem besten Freund des Ex ausgehen.",
  "Fremdgehen im Urlaub zählt genauso wie zu Hause.",
  "Wer betrügt, sollte es niemals gestehen.",
  "Man sollte spätestens beim dritten Date wissen, ob es passt.",
  "Eine offene Beziehung ist genauso ernst wie eine monogame.",
  "Liebe auf den ersten Blick gibt es nicht.",
  "Man sollte den Wohnort niemals für eine Beziehung wechseln.",
  "Ex-Partner sollte man aus sozialen Medien löschen.",
  "Ein One-Night-Stand kann genauso bedeutungsvoll sein wie eine lange Beziehung.",
  "Man sollte niemals mit einem Kollegen etwas anfangen.",
  "Heiratsanträge in der Öffentlichkeit sind peinlich, nicht romantisch.",
  "Wer zuerst verzeiht, verliert einen Streit nicht.",
  "Man sollte den Nachnamen bei der Heirat nicht ändern müssen.",
  "Ein Kuss auf einer Party zählt als Fremdgehen.",
  "Man sollte niemals in einer Beziehung getrennte Konten führen.",
  "Romantik stirbt nach der Hochzeit automatisch.",
  "Man sollte den ersten Schritt immer selbst machen, statt zu warten.",
  "Beziehungen sollten offen über den Chatverlauf des anderen verfügen dürfen.",
  "Ein Partner mit hohem Einkommen ist attraktiver.",
  "Man sollte den Partner nie über den Ex reden hören wollen.",
  "Zusammenziehen vor der Hochzeit ist ein Muss.",
  "Man sollte keine Beziehung ohne Sex vor der Ehe führen.",
  "Streit vor anderen Leuten sollte niemals passieren.",
  "Ein Heiratsantrag sollte immer von einer Person geplant werden, nicht gemeinsam.",
  "Paare, die immer nur noch in Wir-Form sprechen, verlieren dabei ein Stück ihrer Individualität.",
  "Verliebtheit hält höchstens zwei Jahre.",
  "Wer öfter Entschuldigungen ausspricht, hat in der Beziehung weniger Macht.",
  "Man sollte den Kontakt zu allen Ex-Partnern komplett abbrechen.",
  "Eine Beziehung mit großem Kinderwunsch-Unterschied ist zum Scheitern verurteilt.",
  "Man sollte niemals länger als ein Jahr ohne Trauschein zusammen sein.",
  "Ferndiagnosen über die Beziehung von Freunden sollte man sich sparen.",
  "Wer zuerst einzieht, sollte auch die Möbel bestimmen.",
  "Beziehungspausen enden fast immer in Trennungen.",
  "Ein Partner, der nicht kochen kann, ist ein Dealbreaker.",
  "Man sollte den Beziehungsstatus immer öffentlich machen.",
  "Eine Paartherapie in Anspruch zu nehmen ist ein Zeichen von Schwäche.",
  "Wer zuerst textet, wirkt automatisch bedürftiger.",
  "Man sollte niemals mit jemandem zusammen sein, der schon einmal fremdgegangen ist.",
  "Romantische Gesten sind wichtiger als große Geschenke.",
  "Beziehungen ohne gemeinsames Hobby funktionieren nicht langfristig.",
  "Ein Heiratsantrag ohne Ring wirkt weniger ernst gemeint.",
  "Man sollte niemals eine Beziehung nur wegen der Familie beenden.",
  "Wer ständig kontrolliert wird, bleibt aus Angst in der Beziehung, nicht aus Liebe.",
  "Man sollte niemals einen Seitensprung als nur einmalig abtun.",
  "Fernbeziehungen scheitern öfter an Vertrauen als an der Distanz.",
  "Man sollte einen Partner niemals wegen des Aussehens verlassen.",
  "Wer schon früh in einer Beziehung von Liebe spricht, meint es meistens ernst.",
  "Man sollte in einer Beziehung niemals den kompletten Freundeskreis des anderen übernehmen.",
  "Silvester allein zu verbringen ist schlimmer als Valentinstag allein zu verbringen.",
  "Man sollte eine Beziehung niemals wegen finanzieller Unterschiede beenden.",
  "Wer den Hochzeitstag vergisst, liebt trotzdem genauso stark.",
  "Man sollte niemals eine Beziehung retten wollen, wenn beide unglücklich sind.",
  "Ein gemeinsames Haustier festigt eine Beziehung mehr als eine gemeinsame Wohnung.",
  "Man sollte den Partner niemals vor Freunden bloßstellen, auch nicht im Scherz.",
  "Wer nach der Trennung sofort daten geht, hat nicht wirklich losgelassen.",
  "Man sollte niemals heiraten, um die eigenen Eltern zufriedenzustellen.",
  "Eine Beziehung ohne gemeinsame Zukunftspläne hat kein Fundament.",
  "Man sollte den Ex niemals schlechtreden, egal wie die Trennung verlief.",
  "Wer in der Beziehung ständig nachgibt, verliert sich selbst.",
  "Man sollte eine Beziehung niemals aus Angst vor dem Alleinsein fortführen.",
  "Mütter sind wichtiger als Väter.",
  "Kinder sollten für Hausarbeit bezahlt werden.",
  "Man sollte seine Kinder nie öffentlich bestrafen.",
  "Einzelkinder sind verwöhnter als Geschwisterkinder.",
  "Eltern sollten das Handy ihrer minderjährigen Kinder kontrollieren dürfen.",
  "Kinder von berufstätigen Müttern kommen genauso gut zurecht wie andere.",
  "Großeltern verwöhnen Enkelkinder zu sehr.",
  "Man sollte als Kind nie gezwungen werden, Verwandte zu umarmen.",
  "Taschengeld sollte an Schulnoten gekoppelt sein.",
  "Scheidungskinder haben es schwerer im Leben.",
  "Eltern sollten sich niemals vor den Kindern streiten.",
  "Ein Kind ohne Geschwister ist im Nachteil.",
  "Man sollte Kinder nicht öffentlich loben, um sie nicht eitel zu machen.",
  "Adoptiveltern lieben genauso stark wie leibliche Eltern.",
  "Kinder sollten schon früh lernen, mit Ablehnung umzugehen.",
  "Das Wort Rabenmutter sollte aus dem Sprachgebrauch verschwinden.",
  "Väter, die in Elternzeit gehen, sind genauso engagiert wie Mütter.",
  "Kinder sollten bei einer Scheidung immer mitentscheiden dürfen, bei wem sie leben.",
  "Strenge Erziehung bringt bessere Ergebnisse als lockere Erziehung.",
  "Man sollte als Erwachsener finanziell komplett unabhängig von den Eltern sein.",
  "Eltern haben das Recht, das Tagebuch ihrer Kinder zu lesen.",
  "Ein Kind zu bekommen verändert eine Beziehung immer zum Besseren.",
  "Patchwork-Familien funktionieren genauso gut wie klassische Familien.",
  "Kinder sollten nicht bei der Berufswahl der Eltern hineinreden dürfen.",
  "Man sollte Kindern niemals eine Notlüge erzählen.",
  "Wer keine eigenen Kinder hat, kann trotzdem gute Erziehungsratschläge geben.",
  "Kinder sollten Weihnachtsgeschenke selbst bezahlen, sobald sie arbeiten.",
  "Großfamilien sind glücklicher als Kleinfamilien.",
  "Eltern sollten das Sorgerecht immer hälftig teilen, egal was passiert ist.",
  "Man sollte Kindern erlauben, in der Schule sitzen zu bleiben, wenn es ihnen hilft.",
  "Erbschaften sollten zu gleichen Teilen unter Geschwistern aufgeteilt werden, unabhängig vom Bedarf.",
  "Kinder sollten schon mit 16 ausziehen dürfen, wenn sie es wollen.",
  "Man sollte niemals über die Erziehungsmethoden anderer Eltern urteilen.",
  "Eltern, die ihre Kinder nicht impfen lassen, handeln unverantwortlich.",
  "Kinder brauchen feste Schlafenszeiten bis ins Teenageralter.",
  "Man sollte als Elternteil nie den Lieblingsplatz unter den Kindern zeigen.",
  "Stiefeltern sollten die gleiche Autorität wie leibliche Eltern haben.",
  "Kinder ohne Bildschirmzeit vor dem 6. Lebensjahr sind im Vorteil.",
  "Man sollte seinen Kindern nie sagen, dass sie etwas nicht können.",
  "Wer als Kind viel Verantwortung tragen musste, ist als Erwachsener stärker.",
  "Eltern sollten Nein sagen dürfen, ohne sich zu erklären.",
  "Ein Kind zu verwöhnen schadet mehr, als es zu verwehren.",
  "Familientreffen sollten Pflicht sein, egal wie sehr man sich streitet.",
  "Man sollte niemals erwarten, dass die eigenen Kinder einen im Alter pflegen.",
  "Kinder lügen genauso oft wie Erwachsene.",
  "Ein Kind sollte nie zwischen Mama und Papa wählen müssen.",
  "Man sollte Kindern das Sparen beibringen, bevor man ihnen Taschengeld gibt.",
  "Wer keine Kinder will, sollte das nicht rechtfertigen müssen.",
  "Familien, die zusammen essen, halten länger zusammen.",
  "Man sollte niemals Geschwister miteinander vergleichen.",
  "Man sollte Kindern schon früh eigenes Geld verdienen lassen, zum Beispiel durch Ferienjobs.",
  "Großeltern sollten kein Vetorecht bei Erziehungsfragen haben.",
  "Man sollte niemals ein Kind bekommen, um eine Beziehung zu retten.",
  "Halbgeschwister sind genauso Familie wie leibliche Geschwister.",
  "Man sollte Kinder niemals mit Geschenken bestechen, damit sie sich benehmen.",
  "Eltern, die ihre Kinder vergleichen, schaden ihnen fürs Leben.",
  "Man sollte als Elternteil niemals den eigenen Traumberuf für die Kinder aufgeben.",
  "Ein Kind sollte nicht gezwungen werden, ein Instrument zu lernen.",
  "Man sollte Kindern schon früh von Geldproblemen der Familie erzählen.",
  "Erziehungsberatung in Anspruch zu nehmen ist kein Zeichen von Versagen.",
  "Man sollte niemals erwarten, dass erwachsene Kinder jedes Wochenende zu Besuch kommen.",
  "Ein Kind aus einer Patchwork-Familie hat es schwerer als andere.",
  "Man sollte Kindern niemals verbieten, mit den Großeltern allein Zeit zu verbringen.",
  "Strafarbeit als Erziehungsmethode ist längst überholt.",
  "Man sollte als Elternteil niemals die eigene Kindheit als Maßstab nehmen.",
  "Kinder sollten früh lernen, mit Verlust umzugehen, auch bei Haustieren.",
  "Man sollte niemals einem Kind seine erste Beziehung ausreden.",
  "Eltern sollten sich bei ihren Kindern für Fehler entschuldigen können.",
  "Man sollte Enkelkindern niemals mehr schenken als den eigenen Kindern früher.",
  "Ein Kind, das nie Grenzen erfahren hat, hat es später schwerer.",
  "Man sollte niemals über das Sorgerecht streiten, ohne die Kinder zu fragen, was sie wollen.",
  "Eltern, die ihre Kinder nicht loslassen können, schaden der Beziehung.",
  "Man sollte als Familie niemals Weihnachten getrennt verbringen, auch bei einer Scheidung.",
  "Kinder aus kinderreichen Familien sind sozial kompetenter.",
  "Man sollte niemals erwarten, dass Geschwister sich automatisch nahestehen.",
  "Eltern sollten ihren Kindern schon früh das Nein-Sagen beibringen.",
  "Man sollte als Familie niemals über Erbfragen schweigen, bis es zu spät ist.",
  "Kinder, die viel Taschengeld bekommen, gehen später schlechter mit Geld um.",
  "Man sollte niemals das eigene Kind für die Fehler der Erziehung verantwortlich machen.",
  "Eltern sollten öfter zugeben, wenn sie überfordert sind.",
  "Männer sollten beim ersten Date immer bezahlen.",
  "Männer weinen sollten genauso akzeptiert sein wie bei Frauen.",
  "Hausarbeit sollte strikt 50/50 aufgeteilt werden.",
  "Frauen sollten den ersten Schritt beim Daten machen dürfen.",
  "Männer sollten genauso lange Elternzeit nehmen wie Frauen.",
  "Ein Mann, der zu Hause bleibt, während die Frau arbeitet, ist genauso männlich.",
  "Frauen sind emotional stärker als Männer.",
  "Männer sollten sich nicht schämen, Make-up zu tragen.",
  "Der Nachname der Familie sollte nicht automatisch der des Mannes sein.",
  "Frauen sollten beim Heiratsantrag genauso oft fragen wie Männer.",
  "Männer und Frauen führen Beziehungen grundsätzlich unterschiedlich.",
  "Rosa für Mädchen und Blau für Jungs ist überholtes Denken.",
  "Ein Mann ohne festen Job ist für viele Frauen kein Traumpartner.",
  "Frauen sollten in gemischten Gruppen genauso oft den Abend planen wie Männer.",
  "Männer sollten öffentlich über ihre Gefühle sprechen können, ohne als schwach zu gelten.",
  "Frauen, die keine Kinder wollen, werden härter beurteilt als Männer.",
  "Ein Mann sollte niemals eine Frau um Erlaubnis bitten müssen, mit Freunden wegzugehen.",
  "Männer sollten genauso oft sagen, dass sie ihren Partner vermissen, wie Frauen.",
  "Die klassische Rollenverteilung in der Familie funktioniert am besten.",
  "Frauen sollten beim Sport genauso viel verdienen wie Männer.",
  "Ein Mann, der kocht und putzt, ist attraktiver.",
  "Frauen sollten in der Selbstverteidigung genauso trainiert werden wie Männer.",
  "Männer werden für dasselbe Verhalten wie Frauen oft anders bewertet.",
  "Care-Arbeit sollte bezahlt werden, egal wer sie leistet.",
  "Ein Mann, der sich um sein Aussehen kümmert, ist eitel.",
  "Frauen sollten beim Autokauf genauso ernst genommen werden wie Männer.",
  "Männer sollten öffentlich Zärtlichkeit zeigen dürfen, ohne komisch angeschaut zu werden.",
  "Der Muttertag ist wichtiger als der Vatertag.",
  "Frauen tragen in Beziehungen meist die emotionale Hauptlast.",
  "Ein Mann sollte nie kürzer sein als seine Partnerin.",
  "Frauen, die keine Beziehung wollen, gelten schneller als kalt.",
  "Männer sollten genauso streng bei der Kleiderwahl beurteilt werden wie Frauen.",
  "Es sollte normal sein, wenn die Frau mehr verdient als der Mann.",
  "Ein Mann, der weint, verliert nicht an Respekt.",
  "Frauen sollten in technischen Berufen genauso gefördert werden wie Männer.",
  "Männer sollten öfter über ihre mentale Gesundheit sprechen.",
  "Das Konzept von Männersache und Frauensache gehört abgeschafft.",
  "Frauen empfinden Trennungen intensiver als Männer.",
  "Ein Vater, der wickelt, ist genauso normal wie eine Mutter, die es tut.",
  "Männer sollten genauso oft nach dem Wohlbefinden ihres Partners fragen.",
  "Frauen sollten genauso oft zum Wehrdienst oder sozialen Dienst verpflichtet werden wie Männer.",
  "Ein Mann, der seine Partnerin finanziell unterstützt, sollte nicht abfällig betitelt werden.",
  "Frauen sollten sich abends genauso frei bewegen können wie Männer, ohne Angst zu haben.",
  "Männer werden in Sorgerechtsfragen vor Gericht benachteiligt.",
  "Frauen sollten in Führungspositionen eine Quote haben, bis echte Gleichheit erreicht ist.",
  "Ein Mann sollte beim ersten Treffen mit den Eltern der Partnerin genauso nervös sein dürfen wie umgekehrt.",
  "Frauen tragen in Trennungen häufiger die Hauptlast der Kinderbetreuung, weil es gesellschaftlich erwartet wird.",
  "Männer sollten sich öfter um ihre Gesundheit kümmern, ohne dass es als unmännlich gilt.",
  "Der Druck, immer stark sein zu müssen, schadet Männern genauso wie Schönheitsdruck Frauen schadet.",
  "Frauen sollten nicht ständig gefragt werden, wie sie Familie und Job vereinbaren, während Männer das nie gefragt werden.",
  "Ein Mann, der seine Partnerin um Erlaubnis fragt, wirkt nicht schwach, sondern respektvoll.",
  "Frauen sollten körperlich genauso hart rangenommen werden im Training wie Männer.",
  "Männer sollten öfter zu Arztterminen ihrer Partnerin mitgehen, ohne dass es als unnötig gilt.",
  "Die Erwartungshaltung, dass Männer immer den Umzug tragen, ist überholt.",
  "Frauen sollten sich nicht dafür rechtfertigen müssen, dass sie kinderlos glücklich sind.",
  "Ein Mann, der nicht Autofahren kann, wird stärker verurteilt als eine Frau in gleicher Lage.",
  "Männer sollten genauso häufig zu Vorsorgeuntersuchungen ermutigt werden wie Frauen.",
  "Frauen, die laut ihre Meinung sagen, werden schneller als zickig abgestempelt als Männer als durchsetzungsstark.",
  "Ein Mann sollte sich nicht schämen, wenn er in der Beziehung die emotional sensiblere Person ist.",
  "Frauen sollten in gemischten Sportarten die gleichen Regeln haben wie Männer.",
  "Ein hohes Gehalt ist wichtiger als ein Job, der Spaß macht.",
  "Man sollte niemals für Familie oder Freunde arbeiten.",
  "Geld macht glücklich.",
  "Man sollte nie mehr als 50 Stunden pro Woche arbeiten.",
  "Ein Studium lohnt sich nicht mehr wie früher.",
  "Man sollte über sein Gehalt mit Kollegen sprechen.",
  "Wer nicht spart, hat kein Recht, sich über Geldsorgen zu beschweren.",
  "Homeoffice macht produktiver als das Büro.",
  "Man sollte niemals einen Kredit für den Urlaub aufnehmen.",
  "Erfolg im Beruf ist wichtiger als Erfolg im Privatleben.",
  "Man sollte für Geld auch Jobs machen, die einem nicht gefallen.",
  "Ein Chef sollte niemals ein Freund sein.",
  "Man sollte kündigen, sobald man unglücklich im Job ist.",
  "Überstunden sollten immer bezahlt werden, nie nur mit Freizeit ausgeglichen.",
  "Wer viel verdient, sollte auch mehr Steuern zahlen.",
  "Ein Nebenjob neben dem Studium schadet den Noten.",
  "Man sollte niemals unter seinem Marktwert arbeiten.",
  "Erbschaften sollten hoch besteuert werden.",
  "Freelancer haben ein besseres Leben als Angestellte.",
  "Man sollte im Bewerbungsgespräch nie die Wahrheit über Gehaltsvorstellungen sagen.",
  "Ein Startup zu gründen ist riskanter als es wert ist.",
  "Man sollte sich nie für einen Kollegen im Job aufopfern.",
  "Wer im Homeoffice arbeitet, arbeitet weniger als im Büro.",
  "Man sollte immer für das Geld verhandeln, das man verdient.",
  "Reiche Menschen sind nicht automatisch glücklicher.",
  "Man sollte niemals einen Job nur wegen des Prestiges annehmen.",
  "Trinkgeld sollte gesetzlich verpflichtend sein.",
  "Man sollte lieber wenig verdienen und Zeit haben, als viel verdienen und keine Zeit.",
  "Ein Firmenwagen ist wichtiger als ein höheres Gehalt.",
  "Man sollte niemals einem Freund Geld leihen.",
  "Karriere sollte vor der Familienplanung stehen.",
  "Man sollte nie in Aktien investieren, die man nicht versteht.",
  "Ein Uni-Abschluss garantiert keinen besseren Job mehr.",
  "Man sollte immer einen Notgroschen für sechs Monate haben.",
  "Wer im Lotto gewinnt, sollte sofort kündigen.",
  "Man sollte niemals Schulden für Statussymbole machen.",
  "Praktika sollten immer bezahlt werden.",
  "Man sollte den Arbeitgeber wechseln, um mehr zu verdienen, statt auf Loyalität zu setzen.",
  "Ein Vier-Tage-Woche-Modell steigert die Produktivität.",
  "Man sollte niemals in der Probezeit kündigen.",
  "Finanzielle Unabhängigkeit ist wichtiger als ein Traumjob.",
  "Man sollte im Job niemals über Politik sprechen.",
  "Wer im Büro am lautesten ist, kommt beruflich am weitesten.",
  "Man sollte sich nie für ein Gehalt schämen, das man verhandelt hat.",
  "Influencer haben einen echten Beruf.",
  "Man sollte niemals einen Job annehmen, nur weil die Bezahlung gut ist.",
  "Networking ist wichtiger als fachliche Kompetenz.",
  "Man sollte sich niemals für eine Beförderung verbiegen.",
  "Ein eigenes Unternehmen ist erstrebenswerter als ein sicherer Job.",
  "Man sollte Geld niemals als Statussymbol zur Schau stellen.",
  "Man sollte niemals einen Job kündigen, ohne einen neuen sicher zu haben.",
  "Ein bedingungsloses Grundeinkommen würde die Gesellschaft verbessern.",
  "Man sollte niemals mehr als ein Drittel des Einkommens für Miete ausgeben.",
  "Wer im Lotto gewinnt, sollte es der Familie sofort erzählen.",
  "Man sollte niemals einen Kredit aufnehmen, um in Aktien zu investieren.",
  "Erfolgreiche Menschen arbeiten härter als andere, nicht nur klüger.",
  "Man sollte niemals eine Gehaltserhöhung ablehnen, aus Angst vor mehr Verantwortung.",
  "Selbstständigkeit ist riskanter, aber erfüllender als Festanstellung.",
  "Man sollte niemals für ein Unternehmen arbeiten, dessen Werte man nicht teilt.",
  "Ein Chef, der nie Überstunden macht, kann sein Team nicht wirklich verstehen.",
  "Man sollte niemals länger als fünf Jahre im selben Job ohne Beförderung bleiben.",
  "Boni sollten fairer verteilt werden als nach Hierarchieebene.",
  "Man sollte niemals private Probleme mit ins Büro nehmen.",
  "Ein Vier-Tage-Woche-Modell sollte gesetzlich verpflichtend werden.",
  "Man sollte niemals einen Kollegen wegen einer Beförderung schlechtmachen.",
  "Reichtum, der geerbt wurde, ist weniger wert als selbst erarbeiteter.",
  "Man sollte niemals mit dem Gehalt prahlen, auch nicht im engsten Freundeskreis.",
  "Ein Unternehmen sollte Mitarbeiter nie ohne Vorwarnung entlassen dürfen.",
  "Man sollte niemals mehr sparen, als man zum Leben braucht.",
  "Finanzielle Bildung sollte Pflichtfach in der Schule sein.",
  "Man sollte einen Freund verpetzen, wenn er fremdgeht.",
  "Man sollte niemals einer Notlüge zustimmen, um einen Freund zu decken.",
  "Freundschaften zwischen Ex-Partnern sind unmöglich.",
  "Man sollte einem Freund immer die Wahrheit sagen, auch wenn es wehtut.",
  "Wer einen Freund anlügt, um ihn zu schützen, handelt richtig.",
  "Man sollte niemals mit dem Ex eines Freundes ausgehen.",
  "Freundschaft sollte wichtiger sein als eine neue Beziehung.",
  "Man sollte einen Freund melden, wenn er etwas Illegales tut.",
  "Wer als Erster einen Streit mit einem Freund anspricht, ist der Reifere.",
  "Man sollte niemals eine Freundschaft wegen eines Partners beenden.",
  "Alte Freundschaften sind wertvoller als neue.",
  "Man sollte einem Freund sagen, wenn sein Partner ihn betrügt, auch ohne Beweise.",
  "Wer eine Notlüge erzählt, um Gefühle zu schonen, tut das Richtige.",
  "Man sollte niemals für einen Freund lügen, wenn die Polizei fragt.",
  "Freundschaften, die nur online bestehen, sind genauso echt wie welche im echten Leben.",
  "Man sollte einen betrunkenen Freund niemals allein nach Hause lassen, auch gegen seinen Willen.",
  "Wer einen Fund nicht abgibt, ist kein Dieb.",
  "Man sollte einen Freund konfrontieren, wenn er sich in eine toxische Beziehung begibt.",
  "Freundschaften enden zu Recht, wenn sich die Lebenswege trennen.",
  "Man sollte einem Freund niemals Geld schulden, ohne einen Rückzahlungsplan zu haben.",
  "Wer ein gefundenes Portemonnaie mit Geld für sich behält, hat kein Unrecht getan, solange niemand es merkt.",
  "Man sollte niemals eine Gruppenreise mit mehr als vier Freunden planen.",
  "Freunde, die sich nie streiten, sind keine echten Freunde.",
  "Man sollte einem Freund sagen, dass sein neuer Partner nicht gut für ihn ist.",
  "Wer ein Geheimnis eines Freundes ausplaudert, sollte die Freundschaft verlieren.",
  "Man sollte niemals einen Freund um ein Alibi bitten.",
  "Freundschaft heißt, auch bei einem Umzug in eine andere Stadt in Kontakt zu bleiben, komme was wolle.",
  "Man sollte eine Notlüge nutzen, um aus einer ungewollten Verabredung rauszukommen.",
  "Wer im Restaurant zu wenig bezahlt, weil die Rechnung falsch war, sollte es melden.",
  "Man sollte einem Freund niemals sagen, dass man seinen Job hasst, den er ihm vermittelt hat.",
  "Freundschaften mit dem Chef sind riskanter als sie wert sind.",
  "Man sollte immer helfen, wenn ein Fremder auf der Straße um Geld bittet.",
  "Wer schwarzfährt, tut niemandem wirklich weh.",
  "Man sollte einem Freund niemals verheimlichen, dass man seine Schwester attraktiv findet.",
  "Freunde sollten sich gegenseitig bei Umzügen immer helfen, ohne zu fragen.",
  "Man sollte eine gefundene Prüfungsantwort nicht nutzen, selbst wenn niemand es merkt.",
  "Wer im Supermarkt zu wenig bezahlt bekommt, sollte das Wechselgeld korrigieren.",
  "Man sollte niemals einem Freund zuliebe eine Lüge gegenüber der eigenen Familie erzählen.",
  "Freundschaften sollten wichtiger sein als das Streben nach Karriere.",
  "Man sollte einen Freund niemals kritisieren, wenn er nicht danach fragt.",
  "Wer ein Haustier findet und keinen Besitzer sucht, handelt falsch.",
  "Man sollte niemals eine Beziehung geheim halten vor den besten Freunden.",
  "Freunde sollten sich gegenseitig finanziell absichern können.",
  "Man sollte einen Freund unterstützen, auch wenn man seine Entscheidung für falsch hält.",
  "Wer eine Notlüge nutzt, um einer Feier fernzubleiben, handelt unehrlich.",
  "Man sollte niemals eine Freundschaft aus Bequemlichkeit aufrechterhalten.",
  "Freunde, die sich nur bei Problemen melden, sind keine echten Freunde.",
  "Man sollte einen Fremden nie nach der Uhrzeit fragen, wenn man kein Handy dabei hat.",
  "Wer eine Prüfung abschreibt und nicht erwischt wird, hat trotzdem betrogen.",
  "Man sollte einem Freund niemals sagen, dass seine Beziehung zum Scheitern verurteilt ist.",
  "Man sollte niemals ein Geheimnis eines Freundes an den Partner weitergeben.",
  "Wer eine Party ohne Einladung crasht, sollte rausgeworfen werden.",
  "Man sollte niemals einem Freund seine Unsicherheiten vorhalten, selbst im Streit.",
  "Freunde, die man nur einmal im Jahr sieht, zählen trotzdem als enge Freunde.",
  "Man sollte einen Freund niemals zwingen, sich zwischen zwei anderen Freunden zu entscheiden.",
  "Wer beim Schummeln bei einer Prüfung hilft, macht sich genauso schuldig.",
  "Man sollte niemals einem Freund seine Trauer kleinreden.",
  "Freundschaften mit großem Altersunterschied sind genauso wertvoll wie gleichaltrige.",
  "Man sollte einem Freund niemals aufgrund seines Sternzeichens ungefragt Charaktereigenschaften unterstellen.",
  "Wer ein fremdes WLAN ohne Erlaubnis nutzt, handelt unehrlich.",
  "Man sollte niemals einen Streit über Textnachrichten austragen.",
  "Freunde sollten sich gegenseitig bei einem Umzug in eine andere Stadt nicht böse sein.",
  "Man sollte einem Freund niemals sagen, dass man seine Berufswahl für falsch hält, ungefragt.",
  "Wer ein geliehenes Buch beschädigt, sollte es automatisch ersetzen.",
  "Man sollte niemals eine Einladung annehmen, wenn man eigentlich keine Lust hat.",
  "Freundschaften, die auf gemeinsamem Alkoholkonsum beruhen, sind nicht weniger echt.",
  "Man sollte einem Freund niemals raten, sich zu trennen, ohne beide Seiten zu kennen.",
  "Wer ein Taxi teilt und beim Aussteigen nicht mitzahlt, ist unfair.",
  "Man sollte niemals einen Freund kritisieren, während er gerade eine schwere Zeit durchmacht.",
  "Freunde sollten sich gegenseitig sagen, wenn sie etwas Dummes vorhaben.",
  "Man sollte niemals ein Versprechen brechen, nur weil sich die Umstände geändert haben.",
  "Wer bei einem Umzug abgesagt wird, sollte trotzdem beleidigt sein dürfen.",
  "Man sollte einem Freund niemals seine finanzielle Situation vorhalten.",
  "Freundschaften überstehen politische Meinungsverschiedenheiten nicht immer.",
  "Man sollte niemals einen Freund für ein besseres Angebot versetzen.",
  "Wer eine Notlüge nutzt, um einem Streit aus dem Weg zu gehen, ist feige.",
  "Man sollte niemals erwarten, dass ein Freund immer sofort antwortet.",
  "Freunde, die sich nie gegenseitig besuchen, verlieren die Nähe mit der Zeit.",
  "Man sollte einem Freund niemals sagen, dass man seine Eltern nicht mag.",
  "Wer eine geliehene Sache kaputt macht und schweigt, ist unehrlich.",
  "Social Media macht mehr kaputt als es bringt.",
  "Die ältere Generation hat es leichter gehabt als die heutige.",
  "Man sollte sein Leben nicht nach Likes ausrichten.",
  "Die Jugend von heute ist verwöhnter als frühere Generationen.",
  "Man sollte niemals mehr als eine Stunde am Tag auf Social Media verbringen.",
  "Influencer haben einen schlechten Einfluss auf junge Menschen.",
  "Früher war wirklich alles besser.",
  "Man sollte sein Privatleben niemals öffentlich im Internet teilen.",
  "Die Generation Z ist fauler als frühere Generationen.",
  "Man sollte kein Handy am Esstisch benutzen, egal in welcher Situation.",
  "Dating-Apps haben echte Romantik zerstört.",
  "Man sollte spätestens mit 25 wissen, was man beruflich will.",
  "Die Klimakrise wird von der jüngeren Generation übertrieben dargestellt.",
  "Man sollte kein Foto von jemandem posten, ohne zu fragen.",
  "Fleischkonsum sollte stark eingeschränkt werden.",
  "Man sollte niemals länger als eine Woche ohne Sport auskommen.",
  "Minimalismus macht glücklicher als Konsum.",
  "Man sollte sich nicht schämen, mit über 30 noch bei den Eltern zu wohnen.",
  "Die heutige Jugend hat weniger Respekt vor Autoritäten.",
  "Man sollte niemals ein Meeting machen, wenn eine E-Mail reicht.",
  "Reisen bildet mehr als Studieren.",
  "Man sollte kein Handy mit ins Bett nehmen.",
  "Die alte Generation versteht moderne psychische Gesundheit nicht.",
  "Man sollte spätestens mit 18 ausziehen.",
  "Weniger arbeiten und mehr leben ist wichtiger als Karriere machen.",
  "Man sollte niemals mehr als zwei Streamingdienste gleichzeitig abonniert haben.",
  "Die Generation der Babyboomer trägt Mitschuld an der Klimakrise.",
  "Man sollte sich nicht für seine politische Meinung entschuldigen müssen.",
  "Perfekte Work-Life-Balance ist wichtiger als beruflicher Erfolg.",
  "Man sollte öfter offline sein als online.",
  "Junge Menschen haben es schwerer, ein Eigenheim zu kaufen als frühere Generationen.",
  "Man sollte sich niemals für seinen Kinderwunsch rechtfertigen müssen.",
  "Die Kultur des Cancelns schadet mehr, als sie nützt.",
  "Man sollte niemals länger als einen Tag ohne Antwort auf eine Nachricht lassen.",
  "Konsumverzicht ist wichtiger als jede Umweltpolitik.",
  "Man sollte sich nicht schämen, therapiebedürftig zu sein.",
  "Die heutige Generation redet mehr über psychische Gesundheit, als sie wirklich betroffen ist.",
  "Man sollte niemals einen Trend mitmachen, nur weil alle es tun.",
  "Ein Leben ohne Auto ist in den meisten Städten machbar.",
  "Man sollte spätestens mit 30 finanziell auf eigenen Beinen stehen.",
  "Die Generation der Eltern hatte mehr Gemeinschaftssinn als die heutige.",
  "Man sollte niemals mehr Zeit mit dem Smartphone als mit echten Menschen verbringen.",
  "Nachhaltigkeit sollte über Bequemlichkeit stehen.",
  "Man sollte sich nicht für introvertiertes Verhalten entschuldigen.",
  "Die junge Generation ist digitaler, aber einsamer als frühere.",
  "Man sollte kein schlechtes Gewissen wegen Selfcare-Ausgaben haben.",
  "Home-Office sollte zum Standard werden, nicht die Ausnahme.",
  "Man sollte niemals länger als drei Jahre am selben Ort wohnen bleiben, um nicht stehenzubleiben.",
  "Die heutige Jugend ist toleranter als frühere Generationen.",
  "Man sollte kein Ferienhaus besitzen, wenn andere kein Zuhause haben.",
  "Man sollte niemals ein Buch bewerten, ohne es ganz gelesen zu haben.",
  "Streamingdienste haben das Kinoerlebnis überflüssig gemacht.",
  "Man sollte niemals mehr als eine Stunde am Stück fernsehen.",
  "Die Vier-Tage-Woche ist wichtiger als ein höheres Gehalt.",
  "Man sollte niemals einen Trend nur wegen Social Media mitmachen.",
  "Vegan zu leben ist die verantwortungsvollste Ernährungsform.",
  "Man sollte sich niemals für seinen Musikgeschmack rechtfertigen.",
  "Die Digitalisierung hat das Leben komplizierter statt einfacher gemacht.",
  "Man sollte niemals länger als zwei Wochen ohne Urlaub arbeiten.",
  "Selbstoptimierung durch Apps macht mehr Stress als sie nimmt.",
  "Man sollte sich niemals schuldig fühlen, einen ganzen Tag nichts zu tun.",
  "Die Werbeindustrie trägt eine Mitschuld an Körperbildproblemen.",
  "Man sollte niemals länger als zehn Minuten auf dem Handy scrollen, bevor man aufsteht.",
  "Konsumkritik ist heuchlerisch, wenn man selbst ein Smartphone besitzt.",
  "Man sollte sich niemals für fehlendes Interesse an Nachrichten schämen.",
  "Die Vier-Tage-Woche würde die Wirtschaft nicht schwächen.",
  "Man sollte niemals mehr Geld für Marken ausgeben als nötig.",
  "Achtsamkeit und Meditation sind überbewertete Trends.",
  "Man sollte sich niemals dafür entschuldigen, introvertiert zu sein.",
  "Die Jugend von heute engagiert sich mehr politisch als frühere Generationen.",
  "Man sollte niemals länger als einen Monat ungenutzte Abos bezahlen.",
  "Die Vorstellung von der perfekten Work-Life-Balance ist eine Illusion.",
  "Man sollte sich niemals für seinen Kleidungsstil rechtfertigen müssen.",
  "Ältere Menschen sollten sich mehr Mühe geben, digitale Technik zu verstehen.",
  "Man sollte niemals mehr als drei Social-Media-Plattformen gleichzeitig nutzen.",
  "Man sollte im Kino niemals sein Handy anmachen, auch nicht kurz.",
  "Wer beim Autofahren telefoniert, ist eine Gefahr für alle.",
  "Man sollte im Fahrstuhl niemals telefonieren.",
  "Pünktlichkeit ist wichtiger als ein guter erster Eindruck.",
  "Man sollte im Zug niemals laut Musik ohne Kopfhörer hören.",
  "Wer beim Essen schmatzt, sollte darauf hingewiesen werden.",
  "Man sollte niemals ungefragt bei jemandem im Handy schauen.",
  "Warteschlangen-Vordrängler sollten öffentlich zurechtgewiesen werden.",
  "Man sollte im Restaurant niemals das Personal anschnauzen.",
  "Wer eine Verabredung ohne Absage einfach nicht wahrnimmt, ist respektlos.",
  "Man sollte niemals mit Schuhen auf einem fremden Sofa sitzen.",
  "Nachbarn sollten sich gegenseitig zu lauten Partys einladen, statt sich zu beschweren.",
  "Man sollte im Bus oder Zug immer aufstehen, wenn jemand älter ist.",
  "Wer die Toilette benutzt und nicht spült, hat kein Anstandsgefühl.",
  "Man sollte niemals ohne anzuklopfen ein fremdes Zimmer betreten.",
  "Rauchen in Anwesenheit von Nichtrauchern sollte man immer vorher fragen.",
  "Man sollte im Fitnessstudio die Geräte immer sofort abwischen.",
  "Wer beim Zahlen im Restaurant den Betrag genau teilt, ist kleinlich.",
  "Man sollte niemals länger als 15 Minuten zu spät zu einem Treffen kommen.",
  "Haustiere sollten immer an der Leine geführt werden, auch die bravsten.",
  "Man sollte im Kino niemals während des Films reden.",
  "Wer beim Date das Handy ständig checkt, sollte direkt angesprochen werden.",
  "Man sollte niemals fremde Kinder ungefragt zurechtweisen.",
  "Ein verspätetes Geburtstagsgeschenk ist besser als gar keins.",
  "Man sollte im Flugzeug die Rückenlehne nicht komplett zurückstellen.",
  "Wer im Restaurant laut in sein Handy spricht, stört alle anderen.",
  "Man sollte niemals über das Gewicht einer anderen Person sprechen, egal wie gut gemeint.",
  "Ungebetene Ratschläge zur Erziehung sollte man sich immer sparen.",
  "Man sollte im Kino keine mitgebrachten Snacks knistern lassen.",
  "Wer im Meeting ständig unterbricht, sollte darauf hingewiesen werden.",
  "Man sollte niemals fragen, wie viel jemand verdient.",
  "Ungeduld beim Warten auf die Kaffeemaschine im Büro ist unangebracht.",
  "Man sollte im Supermarkt den Wagen niemals mitten im Gang stehen lassen.",
  "Wer im Kino den Sitz eintritt, sollte sich entschuldigen.",
  "Man sollte niemals das Geschenk eines anderen offen kritisieren.",
  "Ungefragte Komplimente zum Aussehen können auch unangenehm sein.",
  "Man sollte im Restaurant nie das Essen vom Nachbartisch fotografieren.",
  "Wer beim Telefonieren laut wird, sollte den Raum verlassen.",
  "Man sollte niemals das letzte Stück vom gemeinsamen Essen nehmen, ohne zu fragen.",
  "Ungeduld im Straßenverkehr führt öfter zu Unfällen als Ablenkung.",
  "Man sollte im Büro niemals Essen mit starkem Geruch mitbringen.",
  "Wer beim Feiern zu laut ist, sollte von Nachbarn direkt angesprochen werden, nicht die Polizei rufen.",
  "Man sollte niemals eine Einladung kurzfristig absagen, außer bei echtem Notfall.",
  "Ungebetene Gäste sollten trotzdem willkommen geheißen werden.",
  "Man sollte im Wartezimmer niemals laut telefonieren.",
  "Wer beim Grillen kein Fleisch für Vegetarier mitbringt, ist ein schlechter Gastgeber.",
  "Man sollte niemals fremde Pakete für Nachbarn annehmen, ohne zu fragen.",
  "Ungeschminkt aus dem Haus zu gehen sollte völlig normal sein.",
  "Man sollte im Aufzug niemals einen Spiegel-Check machen.",
  "Wer beim Warten in der Schlange laut telefoniert, nervt alle um sich herum.",
  "Man sollte niemals im Kino den Handy-Bildschirm während des Films aufleuchten lassen.",
  "Wer eine Autotür gegen ein fremdes Auto knallt, sollte einen Zettel hinterlassen.",
  "Man sollte niemals mit vollem Mund sprechen.",
  "Öffentliches Naseputzen am Esstisch ist ein No-Go.",
  "Man sollte niemals eine fremde Person ungefragt fotografieren.",
  "Wer beim Date die Rechnung nie anschaut, sollte trotzdem anbieten zu zahlen.",
  "Man sollte niemals laut gähnen, ohne die Hand vor den Mund zu halten.",
  "Parkplätze für Menschen mit Behinderung ohne Berechtigung zu nutzen, ist respektlos.",
  "Man sollte niemals ein fremdes Fahrrad ohne Erlaubnis benutzen, auch nicht kurz.",
  "Wer beim Warten in der Bäckerei drängelt, sollte darauf angesprochen werden.",
  "Man sollte niemals über die Attraktivität des Partners eines Freundes sprechen.",
  "Öffentliches Streiten in der Beziehung sollte man sich immer sparen.",
  "Man sollte niemals das letzte Toilettenpapier nicht ersetzen.",
  "Wer beim Telefonieren im Zug die Freisprechfunktion nutzt, ist rücksichtslos.",
  "Man sollte niemals über den Kontostand eines anderen mutmaßen.",
  "Öffentliches Barfußlaufen in Restaurants ist unangebracht.",
  "Man sollte niemals ein Geschenk sofort nach dem Auspacken kritisieren.",
  "Wer beim Reisen die Kopfstütze im Flugzeug tritt, sollte sich entschuldigen.",
  "Man sollte niemals fragen, wie viel eine Wohnung oder ein Haus gekostet hat.",
  "Die Ellenbogen beim Essen auf dem Tisch abzulegen ist keine große Sache.",
  "Man sollte niemals ein Trinkgeld unter fünf Prozent geben, außer bei wirklich schlechtem Service.",
  "Wer beim Warten an der Ampel hupt, obwohl es noch nicht Grün ist, ist ungeduldig.",
  "Man sollte niemals laut über eine Diät am Esstisch sprechen.",
  "Öffentliches Diskutieren über Beziehungsprobleme vor Fremden ist unangebracht.",
  "Man sollte niemals den Fahrstuhl blockieren, wenn andere aussteigen wollen.",
  "Wer sich beim Warten vordrängelt, sollte öffentlich zurechtgewiesen werden.",
  "Man sollte niemals eine fremde Meinung zum eigenen Aussehen unaufgefordert äußern.",
  "Barfuß auf Zugsitzen zu sitzen ist respektlos gegenüber anderen Fahrgästen.",
  "Man sollte niemals einen fremden Regenschirm ohne zu fragen benutzen.",
  "Wer beim Essen im Restaurant laut über das Essen anderer urteilt, ist unhöflich.",
];

export function pickStatement(exclude: Set<string> = new Set()): string {
  const pool = STATEMENTS.filter((s) => !exclude.has(s));
  const list = pool.length > 0 ? pool : STATEMENTS;
  return list[Math.floor(Math.random() * list.length)];
}
