interface GuessItQuestion {
  question: string;
  answer: number;
  unit: string;
}

const QUESTIONS: GuessItQuestion[] = [
  { question: "Wie viele Haare hat ein durchschnittlicher Mensch auf dem Kopf?", answer: 100000, unit: "Haare" },
  { question: "Wie viele Knochen hat ein erwachsener Mensch?", answer: 206, unit: "Knochen" },
  { question: "Wie lang ist die Chinesische Mauer?", answer: 21196, unit: "km" },
  { question: "Wie viele Zähne hat ein erwachsener Hai im Laufe seines Lebens?", answer: 30000, unit: "Zähne" },
  { question: "Wie viele Menschen leben aktuell auf der Erde?", answer: 8200000000, unit: "Menschen" },
  { question: "Wie hoch ist der Mount Everest?", answer: 8849, unit: "m" },
  { question: "Wie viele Herzen hat ein Krake?", answer: 3, unit: "Herzen" },
  { question: "Wie alt kann eine Galapagos-Riesenschildkröte werden?", answer: 180, unit: "Jahre" },
  { question: "Wie viele Sprachen gibt es weltweit ungefähr?", answer: 7000, unit: "Sprachen" },
  { question: "Wie schnell kann ein Gepard maximal laufen?", answer: 110, unit: "km/h" },
  { question: "Wie viele Liter Blut pumpt ein menschliches Herz pro Tag?", answer: 7500, unit: "Liter" },
  { question: "Wie viele Stufen hat der Eiffelturm?", answer: 1665, unit: "Stufen" },
  { question: "Wie viele Muskeln braucht ein Mensch zum Lächeln?", answer: 12, unit: "Muskeln" },
  { question: "Wie tief ist der tiefste Punkt der Ozeane (Marianengraben)?", answer: 10935, unit: "m" },
  { question: "Wie viele Eier legt ein Huhn im Durchschnitt pro Jahr?", answer: 300, unit: "Eier" },
  { question: "Wie viele Buchstaben hat das längste offizielle deutsche Wort im Duden?", answer: 36, unit: "Buchstaben" },

  // Biologie / Körper
  { question: "Wie viele Muskeln hat der menschliche Körper?", answer: 650, unit: "Muskeln" },
  { question: "Wie viele Kilometer Blutgefäße hat ein erwachsener Mensch im Körper?", answer: 100000, unit: "km" },
  { question: "Wie viele Liter Speichel produziert ein Mensch etwa pro Jahr?", answer: 500, unit: "Liter" },
  { question: "Wie oft schlägt ein menschliches Herz durchschnittlich pro Tag?", answer: 100000, unit: "Schläge" },
  { question: "Wie viele Liter Luft atmet ein Mensch täglich ein?", answer: 11000, unit: "Liter" },
  { question: "Wie viele Meter lang ist der Dünndarm eines Erwachsenen?", answer: 6, unit: "m" },
  { question: "Wie viele Geschmacksknospen hat die menschliche Zunge?", answer: 10000, unit: "Geschmacksknospen" },
  { question: "Wie viele Haare verliert ein Mensch im Schnitt pro Tag?", answer: 100, unit: "Haare" },
  { question: "Wie viele Liter Blut zirkulieren im Körper eines Erwachsenen?", answer: 5, unit: "Liter" },
  { question: "Um wie viele Millimeter wachsen Fingernägel pro Monat?", answer: 3, unit: "mm" },
  { question: "Wie viele Neuronen besitzt das menschliche Gehirn ungefähr?", answer: 86000000000, unit: "Neuronen" },
  { question: "Wie viele Kalorien verbraucht das Gehirn täglich ungefähr?", answer: 400, unit: "kcal" },
  { question: "Aus wie vielen Zellen besteht der menschliche Körper ungefähr?", answer: 37000000000000, unit: "Zellen" },
  { question: "Wie oft blinzelt ein Mensch durchschnittlich pro Tag?", answer: 15000, unit: "Lidschläge" },
  { question: "Wie viele Knochen hat ein neugeborenes Baby?", answer: 300, unit: "Knochen" },
  { question: "Wie viele Rippen hat ein erwachsener Mensch?", answer: 24, unit: "Rippen" },
  { question: "Wie viele Gramm wiegt ein menschliches Gehirn durchschnittlich?", answer: 1400, unit: "g" },
  { question: "Wie viele Zentimeter lang ist der Dickdarm eines Erwachsenen?", answer: 150, unit: "cm" },
  { question: "Wie viele Liter Urin produziert ein Mensch im Schnitt pro Jahr?", answer: 550, unit: "Liter" },
  { question: "Wie viele Wörter spricht ein Mensch im Durchschnitt pro Tag?", answer: 16000, unit: "Wörter" },
  { question: "Nach wie vielen Tagen erneuert sich die menschliche Haut komplett?", answer: 28, unit: "Tage" },
  { question: "Wie viele Liter Schweiß kann ein Mensch an einem heißen Tag maximal verlieren?", answer: 3, unit: "Liter" },
  { question: "Wie hoch ist die normale Körpertemperatur eines gesunden Menschen?", answer: 37, unit: "°C" },
  { question: "Wie viele Atemzüge macht ein Mensch pro Minute im Ruhezustand?", answer: 16, unit: "Atemzüge" },
  { question: "Wie viele Liter Magensäure produziert der Magen täglich?", answer: 2, unit: "Liter" },
  { question: "Wie groß ist die innere Oberfläche der menschlichen Lunge?", answer: 70, unit: "m²" },
  { question: "Wie viele Chromosomen besitzt ein Mensch?", answer: 46, unit: "Chromosomen" },
  { question: "Wie viele Milchzähne hat ein Kind?", answer: 20, unit: "Zähne" },
  { question: "Wie viele Milliliter fasst eine menschliche Blase maximal?", answer: 500, unit: "ml" },
  { question: "Wie viele Prozent des Körpergewichts macht das Blut ungefähr aus?", answer: 8, unit: "%" },
  { question: "Wie viele Stunden schläft ein Neugeborenes durchschnittlich pro Tag?", answer: 16, unit: "Stunden" },
  { question: "Wie viele Kilogramm wiegt die Haut eines erwachsenen Menschen?", answer: 4, unit: "kg" },
  { question: "Wie viele Quadratmeter misst die Haut eines erwachsenen Menschen?", answer: 2, unit: "m²" },
  { question: "Wie viele Jahre dauert es durchschnittlich, bis sich das Skelett komplett erneuert hat?", answer: 10, unit: "Jahre" },
  { question: "Wie viele Milliliter Fruchtwasser umgeben ein ungeborenes Baby kurz vor der Geburt?", answer: 800, unit: "ml" },

  // Tierwelt
  { question: "Wie viele Herzen hat ein Regenwurm?", answer: 5, unit: "Herzen" },
  { question: "Wie schnell kann ein Wanderfalke im Sturzflug werden?", answer: 320, unit: "km/h" },
  { question: "Wie alt kann ein Elefant im Schnitt werden?", answer: 70, unit: "Jahre" },
  { question: "Wie viele Tonnen wiegt ein ausgewachsener Blauwal maximal?", answer: 180, unit: "Tonnen" },
  { question: "Wie lang wird ein ausgewachsener Blauwal maximal?", answer: 30, unit: "m" },
  { question: "Wie viele Beine kann ein Tausendfüßer maximal haben?", answer: 750, unit: "Beine" },
  { question: "Wie viele Meter hoch wird eine ausgewachsene Giraffe?", answer: 5, unit: "m" },
  { question: "In wie vielen Sekunden beschleunigt ein Gepard von 0 auf 100 km/h?", answer: 3, unit: "Sekunden" },
  { question: "Wie viele Eier legt eine Meeresschildkröte pro Gelege durchschnittlich?", answer: 110, unit: "Eier" },
  { question: "Wie alt kann ein Ara-Papagei maximal werden?", answer: 60, unit: "Jahre" },
  { question: "Wie viele Kilogramm frisst ein ausgewachsener Elefant pro Tag?", answer: 150, unit: "kg" },
  { question: "Wie viele Liter Wasser trinkt ein Elefant täglich?", answer: 150, unit: "Liter" },
  { question: "Wie schnell kann ein Löwe maximal rennen?", answer: 80, unit: "km/h" },
  { question: "Wie viele Zentimeter hoch kann ein Floh springen?", answer: 20, unit: "cm" },
  { question: "Wie viele Zähne hat ein erwachsener Hund?", answer: 42, unit: "Zähne" },
  { question: "Wie viele Zähne hat eine Katze?", answer: 30, unit: "Zähne" },
  { question: "Wie viele Tage kann ein Kamel ohne Wasser auskommen?", answer: 14, unit: "Tage" },
  { question: "Wie viele Kilometer weit kann ein Albatros an einem Tag fliegen?", answer: 800, unit: "km" },
  { question: "Wie alt kann ein Grönlandhai werden?", answer: 400, unit: "Jahre" },
  { question: "Wie viele Junge bringt ein Wildschwein durchschnittlich pro Wurf zur Welt?", answer: 5, unit: "Junge" },
  { question: "Wie schnell schlägt das Herz eines Kolibris im Flug pro Minute?", answer: 1200, unit: "Schläge" },
  { question: "Wie viele Kilometer legt ein Monarchfalter auf seiner Wanderung zurück?", answer: 4000, unit: "km" },
  { question: "Wie hoch kann ein Känguru springen?", answer: 3, unit: "m" },
  { question: "Wie schnell kann ein Strauß maximal laufen?", answer: 70, unit: "km/h" },
  { question: "Wie groß wird ein ausgewachsener Afrikanischer Elefant an der Schulter?", answer: 3, unit: "m" },
  { question: "Wie viele Kilogramm wiegt ein ausgewachsenes Gorilla-Männchen?", answer: 180, unit: "kg" },
  { question: "Wie alt kann eine Hauskatze durchschnittlich werden?", answer: 15, unit: "Jahre" },
  { question: "Wie viele Stunden schläft eine Katze durchschnittlich pro Tag?", answer: 15, unit: "Stunden" },
  { question: "Wie viele Stunden schläft eine Giraffe durchschnittlich pro Tag?", answer: 2, unit: "Stunden" },
  { question: "Wie viele Kilometer kann ein Wolf an einem Tag zurücklegen?", answer: 50, unit: "km" },
  { question: "Wie viele Eier legt eine Bienenkönigin an einem guten Tag maximal?", answer: 2000, unit: "Eier" },
  { question: "Wie viele Kilometer fliegt eine Biene ungefähr für 500 Gramm Honig?", answer: 90000, unit: "km" },
  { question: "Wie viele Flügelschläge macht ein Kolibri pro Sekunde?", answer: 50, unit: "Flügelschläge" },
  { question: "Wie viele Kilometer pro Stunde erreicht ein Schwertfisch maximal?", answer: 100, unit: "km/h" },
  { question: "Wie tief kann ein Pottwal maximal abtauchen?", answer: 2000, unit: "m" },
  { question: "Wie lange kann ein Pottwal die Luft anhalten?", answer: 90, unit: "Minuten" },
  { question: "Wie viele Kilogramm wiegt das Herz eines Blauwals ungefähr?", answer: 200, unit: "kg" },
  { question: "Wie schnell kann ein Nilpferd an Land laufen?", answer: 30, unit: "km/h" },
  { question: "Wie viele Kilogramm wiegt ein ausgewachsenes Nilpferd?", answer: 1500, unit: "kg" },
  { question: "Wie alt kann ein Aal werden?", answer: 50, unit: "Jahre" },
  { question: "Wie viele Kilometer weit wandert ein Lachs zum Laichen flussaufwärts maximal?", answer: 3000, unit: "km" },
  { question: "Um wie viele Grad kann sich ein Chamäleon-Auge drehen?", answer: 180, unit: "Grad" },
  { question: "Wie viele Kilogramm Fleisch frisst ein Löwe bei einer Mahlzeit maximal?", answer: 30, unit: "kg" },

  // Geografie / Bauwerke / Sehenswürdigkeiten
  { question: "Wie hoch ist der Eiffelturm?", answer: 330, unit: "m" },
  { question: "Wie viele Stockwerke hat das Empire State Building?", answer: 102, unit: "Stockwerke" },
  { question: "Wie hoch ist das Empire State Building?", answer: 443, unit: "m" },
  { question: "Wie hoch ist der Burj Khalifa, das höchste Gebäude der Welt?", answer: 828, unit: "m" },
  { question: "Wie lang ist der Amazonas?", answer: 6400, unit: "km" },
  { question: "Wie lang ist der Nil?", answer: 6650, unit: "km" },
  { question: "Wie groß ist Russland an Fläche?", answer: 17100000, unit: "km²" },
  { question: "Wie viele Einwohner hat Deutschland ungefähr?", answer: 84000000, unit: "Menschen" },
  { question: "Wie viele Einwohner hat die Metropolregion Tokio ungefähr?", answer: 37000000, unit: "Menschen" },
  { question: "Wie viele Zeitzonen hat Frankreich inklusive Überseegebiete, die meisten weltweit?", answer: 12, unit: "Zeitzonen" },
  { question: "Wie hoch ist der K2, der zweithöchste Berg der Welt?", answer: 8611, unit: "m" },
  { question: "Wie tief ist der Baikalsee, der tiefste See der Welt?", answer: 1642, unit: "m" },
  { question: "Wie groß ist der Bodensee an Fläche?", answer: 536, unit: "km²" },
  { question: "Wie lang ist die Donau?", answer: 2850, unit: "km" },
  { question: "Wie lang ist der Rhein?", answer: 1230, unit: "km" },
  { question: "Wie hoch ist die Zugspitze, Deutschlands höchster Berg?", answer: 2962, unit: "m" },
  { question: "Wie viele Inseln hat Indonesien ungefähr?", answer: 17000, unit: "Inseln" },
  { question: "Wie groß ist die Sahara an Fläche?", answer: 9200000, unit: "km²" },
  { question: "Wie hoch ist die Cheops-Pyramide?", answer: 138, unit: "m" },
  { question: "Wie alt ist die Cheops-Pyramide ungefähr?", answer: 4500, unit: "Jahre" },
  { question: "Wie hoch ist die Freiheitsstatue inklusive Sockel?", answer: 93, unit: "m" },
  { question: "Wie viele Stufen muss man zur Krone der Freiheitsstatue steigen?", answer: 354, unit: "Stufen" },
  { question: "Wie lang ist die Golden Gate Bridge?", answer: 2737, unit: "m" },
  { question: "Wie hoch sind die Pylone der Golden Gate Bridge?", answer: 227, unit: "m" },
  { question: "Wie viele Hektar groß ist der Central Park in New York?", answer: 340, unit: "Hektar" },
  { question: "Wie viele Menschen besuchen den Eiffelturm pro Jahr ungefähr?", answer: 6000000, unit: "Menschen" },
  { question: "Wie tief ist der Grand Canyon an seiner tiefsten Stelle?", answer: 1800, unit: "m" },
  { question: "Wie lang ist der Grand Canyon?", answer: 446, unit: "km" },
  { question: "Wie hoch ist der Angel Falls, der höchste Wasserfall der Welt?", answer: 979, unit: "m" },
  { question: "Wie breit sind die Niagarafälle (Horseshoe Falls)?", answer: 670, unit: "m" },
  { question: "Wie viele Liter Wasser stürzen pro Sekunde über die Niagarafälle?", answer: 168000, unit: "Liter" },
  { question: "Wie hoch ist der Kölner Dom?", answer: 157, unit: "m" },
  { question: "Wie viele Jahre dauerte der Bau des Kölner Doms insgesamt?", answer: 632, unit: "Jahre" },
  { question: "Wie viele Einwohner hat Berlin?", answer: 3700000, unit: "Menschen" },
  { question: "Wie viele Einwohner hat München?", answer: 1500000, unit: "Menschen" },
  { question: "Wie groß ist Luxemburg an Fläche?", answer: 2586, unit: "km²" },
  { question: "Wie viele Hektar groß ist der Vatikan, der kleinste Staat der Welt?", answer: 44, unit: "Hektar" },
  { question: "Wie viele Zeitzonen hat Russland?", answer: 11, unit: "Zeitzonen" },
  { question: "Wie viele Kilometer lang ist die Grenze zwischen den USA und Kanada?", answer: 8891, unit: "km" },
  { question: "Wie hoch liegt La Paz, die höchste Hauptstadt der Welt?", answer: 3640, unit: "m" },
  { question: "Wie viele Kilometer lang ist der Suezkanal?", answer: 193, unit: "km" },
  { question: "Wie viele Kilometer lang ist der Panamakanal?", answer: 82, unit: "km" },
  { question: "Wie viele Schiffe passieren den Panamakanal pro Jahr ungefähr?", answer: 14000, unit: "Schiffe" },
  { question: "Wie groß ist Grönland, die größte Insel der Welt, an Fläche?", answer: 2166000, unit: "km²" },
  { question: "Wie viele Kilometer lang ist die Route 66?", answer: 3940, unit: "km" },
  { question: "Wie hoch ist der Berliner Fernsehturm am Alexanderplatz?", answer: 368, unit: "m" },
  { question: "Wie viele Länder grenzen an Deutschland?", answer: 9, unit: "Länder" },
  { question: "Wie viele Bundesländer hat Deutschland?", answer: 16, unit: "Bundesländer" },
  { question: "Wie viele Kilometer Küste hat Norwegen inklusive Fjorde ungefähr?", answer: 100000, unit: "km" },
  { question: "Wie hoch ist der Mont Blanc, der höchste Berg der Alpen?", answer: 4809, unit: "m" },
  { question: "Wie viele Gletscher gibt es in den Alpen ungefähr?", answer: 4000, unit: "Gletscher" },
  { question: "Wie groß ist der Genfersee an Fläche?", answer: 580, unit: "km²" },
  { question: "Wie viele Kilometer lang ist die Great Ocean Road in Australien?", answer: 243, unit: "km" },
  { question: "Wie hoch ist der Tafelberg in Kapstadt?", answer: 1085, unit: "m" },

  // Weltraum / Astronomie
  { question: "Wie viele Kilometer ist die Erde vom Mond durchschnittlich entfernt?", answer: 384400, unit: "km" },
  { question: "Wie viele Kilometer ist die Erde von der Sonne durchschnittlich entfernt?", answer: 150000000, unit: "km" },
  { question: "Wie groß ist der Durchmesser der Sonne?", answer: 1392000, unit: "km" },
  { question: "Wie groß ist der Durchmesser der Erde?", answer: 12742, unit: "km" },
  { question: "Wie viele Minuten braucht das Licht von der Sonne bis zur Erde?", answer: 8, unit: "Minuten" },
  { question: "Wie viele Planeten hat unser Sonnensystem?", answer: 8, unit: "Planeten" },
  { question: "Wie viele bekannte Monde hat der Planet Jupiter?", answer: 95, unit: "Monde" },
  { question: "Wie viele bekannte Monde hat der Planet Saturn?", answer: 146, unit: "Monde" },
  { question: "Wie viele Erdtage dauert ein Sonnentag auf dem Merkur?", answer: 176, unit: "Erdtage" },
  { question: "Wie viele Erdjahre dauert ein Jahr auf dem Jupiter?", answer: 12, unit: "Jahre" },
  { question: "Wie viele Erdjahre dauert ein Jahr auf dem Saturn?", answer: 29, unit: "Jahre" },
  { question: "Wie schnell dreht sich die Erde am Äquator?", answer: 1670, unit: "km/h" },
  { question: "Wie schnell umkreist die Erde die Sonne?", answer: 107000, unit: "km/h" },
  { question: "Wie viele Jahre alt ist das Universum ungefähr?", answer: 13800000000, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist unser Sonnensystem ungefähr?", answer: 4600000000, unit: "Jahre" },
  { question: "Wie viele Sterne enthält die Milchstraße ungefähr?", answer: 200000000000, unit: "Sterne" },
  { question: "Wie viele Lichtjahre misst der Durchmesser der Milchstraße?", answer: 100000, unit: "Lichtjahre" },
  { question: "Wie viele Monate dauert ein Flug zum Mars mit heutiger Technik ungefähr?", answer: 7, unit: "Monate" },
  { question: "Wie viele Astronauten waren bisher insgesamt auf dem Mond?", answer: 12, unit: "Astronauten" },
  { question: "Wie viele Tage dauerte die Mondlandungs-Mission Apollo 11 insgesamt?", answer: 8, unit: "Tage" },
  { question: "Wie schnell fliegt die Internationale Raumstation ISS um die Erde?", answer: 28000, unit: "km/h" },
  { question: "Wie hoch fliegt die ISS über der Erde ungefähr?", answer: 400, unit: "km" },
  { question: "Wie viele Minuten braucht die ISS für eine komplette Erdumrundung?", answer: 90, unit: "Minuten" },
  { question: "Wie viele Monde hat der Mars?", answer: 2, unit: "Monde" },
  { question: "Wie viele Grad Celsius herrschen auf der Oberfläche der Venus?", answer: 460, unit: "°C" },
  { question: "Wie groß ist der Durchmesser des Mondes?", answer: 3474, unit: "km" },
  { question: "Wie groß ist der Durchmesser des Jupiters?", answer: 139820, unit: "km" },
  { question: "Wie viele Erden würden dem Volumen nach in die Sonne passen?", answer: 1300000, unit: "Erden" },
  { question: "Wie viele Tonnen Weltraumstaub und Meteoriten treffen täglich auf die Erde?", answer: 100, unit: "Tonnen" },
  { question: "Wie viele Lichtjahre ist der nächste Stern Proxima Centauri von der Erde entfernt?", answer: 4, unit: "Lichtjahre" },
  { question: "Wie viele Galaxien gibt es im beobachtbaren Universum schätzungsweise?", answer: 2000000000000, unit: "Galaxien" },
  { question: "Wie viele Kilometer pro Sekunde legt das Licht zurück?", answer: 300000, unit: "km/s" },
  { question: "Wie viele Tage dauert eine komplette Mondumkreisung der Erde?", answer: 27, unit: "Tage" },
  { question: "Wie viele Tage dauert eine Rotation der Sonne am Äquator um die eigene Achse?", answer: 27, unit: "Tage" },
  { question: "Wie viele Raketenstarts gab es weltweit im Jahr 2023 ungefähr?", answer: 220, unit: "Starts" },
  { question: "Wie viele aktive künstliche Satelliten umkreisen die Erde ungefähr?", answer: 9000, unit: "Satelliten" },
  { question: "Wie viele Kilometer misst der Große Rote Fleck auf dem Jupiter im Durchmesser?", answer: 16000, unit: "km" },
  { question: "Wie viele Meter misst der Hauptspiegel des James-Webb-Weltraumteleskops im Durchmesser?", answer: 6.5, unit: "m" },
  { question: "Wie viele Jahre brauchte die Raumsonde Voyager 1, um den Rand des Sonnensystems zu erreichen?", answer: 35, unit: "Jahre" },
  { question: "Wie viele Kilometer hat die Raumsonde Voyager 1 bisher ungefähr zurückgelegt?", answer: 24000000000, unit: "km" },

  // Geschichte (Zeitspannen)
  { question: "Wie viele Jahre dauerte der Bau der Chinesischen Mauer insgesamt über mehrere Dynastien?", answer: 2000, unit: "Jahre" },
  { question: "Wie viele Jahre bestand das weströmische Reich ungefähr?", answer: 500, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Gutenberg den Buchdruck erfand?", answer: 585, unit: "Jahre" },
  { question: "Wie viele Jahre dauerte der Hundertjährige Krieg tatsächlich?", answer: 116, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist die Mona Lisa ungefähr?", answer: 520, unit: "Jahre" },
  { question: "Wie viele Jahre regierte Königin Elizabeth II. von Großbritannien?", answer: 70, unit: "Jahre" },
  { question: "Wie viele Jahre war Berlin durch die Mauer geteilt?", answer: 28, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass der erste Mensch den Mond betrat?", answer: 57, unit: "Jahre" },
  { question: "Wie viele Jahre dauerte die Regierungszeit von Ludwig XIV., dem Sonnenkönig?", answer: 72, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist die Universität Bologna, die älteste Universität Europas?", answer: 935, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Kolumbus in Amerika ankam?", answer: 534, unit: "Jahre" },
  { question: "Wie viele Jahre dauerte der Bau von Notre-Dame in Paris?", answer: 182, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist das Kolosseum in Rom ungefähr?", answer: 1950, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass der erste Benz Patent-Motorwagen gebaut wurde?", answer: 140, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass die Titanic sank?", answer: 114, unit: "Jahre" },
  { question: "Wie viele Jahre dauerte die industrielle Revolution in Europa ungefähr?", answer: 100, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass die Berliner Mauer fiel?", answer: 37, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass das World Wide Web erfunden wurde?", answer: 37, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist die Freiheitsstatue?", answer: 140, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Deutschland wiedervereinigt wurde?", answer: 36, unit: "Jahre" },
  { question: "Wie viele Jahre regierten die Habsburger über Österreich ungefähr?", answer: 600, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist die durchgehende chinesische Zivilisation ungefähr?", answer: 3500, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass das erste Telefon patentiert wurde?", answer: 150, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Marie Curie den Nobelpreis für Physik erhielt?", answer: 123, unit: "Jahre" },
  { question: "Wie viele Jahre alt ist die Universität Oxford ungefähr?", answer: 930, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass das erste Mobiltelefon vorgestellt wurde?", answer: 53, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass die ersten Olympischen Spiele der Neuzeit stattfanden?", answer: 130, unit: "Jahre" },
  { question: "Wie viele Jahre bestand die Sowjetunion?", answer: 69, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Einstein die Relativitätstheorie veröffentlichte?", answer: 121, unit: "Jahre" },

  // Sport-Rekorde
  { question: "Wie schnell lief Usain Bolt bei seinem 100-Meter-Weltrekord im Durchschnitt?", answer: 38, unit: "km/h" },
  { question: "Wie viele Sekunden benötigte Usain Bolt für seinen 100-Meter-Weltrekord?", answer: 9.58, unit: "Sekunden" },
  { question: "Wie viele Tore erzielte Lionel Messi in seinem torreichsten Kalenderjahr?", answer: 91, unit: "Tore" },
  { question: "Wie viele Formel-1-Weltmeistertitel hat Michael Schumacher gewonnen?", answer: 7, unit: "Titel" },
  { question: "Wie viele olympische Goldmedaillen hat Michael Phelps insgesamt gewonnen?", answer: 23, unit: "Goldmedaillen" },
  { question: "Wie viele Kilometer lang ist ein Marathon?", answer: 42, unit: "km" },
  { question: "Wie viele Spieler stehen bei einem Fußballspiel gleichzeitig auf dem Feld, beide Teams zusammen?", answer: 22, unit: "Spieler" },
  { question: "Wie viele Minuten dauert ein reguläres Fußballspiel ohne Nachspielzeit?", answer: 90, unit: "Minuten" },
  { question: "Wie viele Etappen umfasst die Tour de France ungefähr?", answer: 21, unit: "Etappen" },
  { question: "Wie viele Kilometer lang ist die Tour de France insgesamt ungefähr?", answer: 3500, unit: "km" },
  { question: "Wie viele Spieler stehen bei einer Basketballmannschaft pro Team auf dem Feld?", answer: 5, unit: "Spieler" },
  { question: "Wie viele Zentimeter hoch hängt ein Basketballkorb?", answer: 305, unit: "cm" },
  { question: "Wie viele Runden dauert ein WM-Boxkampf im Profiboxen maximal?", answer: 12, unit: "Runden" },
  { question: "Wie viele Kilometer pro Stunde erreicht ein Tennisaufschlag bei Profis maximal?", answer: 260, unit: "km/h" },
  { question: "Wie viele Sätze müssen Männer bei Grand-Slam-Turnieren maximal gewinnen?", answer: 3, unit: "Sätze" },
  { question: "Wie viele Spieler stehen bei einer Volleyballmannschaft auf dem Feld?", answer: 6, unit: "Spieler" },
  { question: "Wie hoch hängt ein Volleyballnetz bei den Männern?", answer: 243, unit: "cm" },
  { question: "Wie viele Kilogramm hebt ein Weltrekordhalter im Gewichtheben beim Reißen maximal?", answer: 225, unit: "kg" },
  { question: "Wie viele Meter weit sprang der Weltrekordhalter im Weitsprung?", answer: 8.95, unit: "m" },
  { question: "Wie viele Meter hoch sprang der Stabhochsprung-Weltrekordhalter?", answer: 6.24, unit: "m" },
  { question: "Wie viele Meter lang ist eine olympische Schwimmbahn?", answer: 50, unit: "m" },
  { question: "Wie viele Spieler stehen bei einer Eishockeymannschaft pro Team auf dem Eis?", answer: 6, unit: "Spieler" },
  { question: "Wie viele Minuten dauert die reine Spielzeit eines Eishockeyspiels?", answer: 60, unit: "Minuten" },
  { question: "Wie viele Löcher hat eine normale Golfrunde?", answer: 18, unit: "Löcher" },
  { question: "Wie viele Kilometer lang ist eine Formel-1-Strecke im Schnitt pro Runde?", answer: 5, unit: "km" },
  { question: "Wie viele Runden umfasst ein Formel-1-Rennen im Schnitt?", answer: 60, unit: "Runden" },
  { question: "Wie schnell fährt ein Formel-1-Auto in der Spitze?", answer: 350, unit: "km/h" },
  { question: "Wie viele Kilometer läuft ein Fußballspieler durchschnittlich pro Spiel?", answer: 10, unit: "km" },
  { question: "Wie viele Fußball-Weltmeistertitel hat Brasilien gewonnen?", answer: 5, unit: "Titel" },
  { question: "Wie viele Länder nehmen am Finalturnier einer Fußball-Weltmeisterschaft teil?", answer: 32, unit: "Länder" },
  { question: "Wie viele Spiele umfasst eine NBA-Hauptrundensaison pro Team?", answer: 82, unit: "Spiele" },
  { question: "Wie viele Kilometer lang ist ein Ironman-Triathlon insgesamt?", answer: 226, unit: "km" },
  { question: "Wie viele Meter misst eine olympische Laufbahn einmal rundherum?", answer: 400, unit: "m" },
  { question: "Wie viele Spieler stehen bei einem Rugby-Union-Team auf dem Feld?", answer: 15, unit: "Spieler" },
  { question: "Wie viele Minuten dauert ein Viertel im American Football an reiner Spielzeit?", answer: 15, unit: "Minuten" },
  { question: "Wie viele Kilogramm wiegt eine Kugel beim Kugelstoßen der Männer?", answer: 7, unit: "kg" },
  { question: "Wie viele Athleten nehmen an Olympischen Sommerspielen ungefähr teil?", answer: 10500, unit: "Athleten" },
  { question: "Wie viele Sportarten umfassen die Olympischen Sommerspiele ungefähr?", answer: 32, unit: "Sportarten" },
  { question: "Wie viele Kilometer schwimmt ein Spitzenschwimmer im Training pro Woche ungefähr?", answer: 60, unit: "km" },
  { question: "Wie viele Vereine spielen in der 1. Fußball-Bundesliga?", answer: 18, unit: "Vereine" },

  // Technik / Erfindungen
  { question: "Wie viele Apps gibt es ungefähr im Apple App Store?", answer: 1800000, unit: "Apps" },
  { question: "Wie viele Websites gibt es weltweit ungefähr?", answer: 1100000000, unit: "Websites" },
  { question: "Wie viele Menschen nutzen weltweit ungefähr das Internet?", answer: 5400000000, unit: "Menschen" },
  { question: "Wie viele WhatsApp-Nachrichten werden weltweit pro Tag verschickt ungefähr?", answer: 100000000000, unit: "Nachrichten" },
  { question: "Wie viele Google-Suchanfragen werden weltweit pro Sekunde gestellt ungefähr?", answer: 99000, unit: "Suchanfragen" },
  { question: "Wie viele Transistoren hat ein moderner High-End-Computerchip ungefähr?", answer: 50000000000, unit: "Transistoren" },
  { question: "Wie viele Jahre ist es her, dass das erste iPhone vorgestellt wurde?", answer: 19, unit: "Jahre" },
  { question: "Wie viele Jahre ist es her, dass Facebook gegründet wurde?", answer: 22, unit: "Jahre" },
  { question: "Wie viele aktive Nutzer hat YouTube monatlich ungefähr?", answer: 2700000000, unit: "Nutzer" },
  { question: "Wie viele Stunden Videomaterial werden pro Minute auf YouTube hochgeladen ungefähr?", answer: 500, unit: "Stunden" },
  { question: "Wie viele Farben kann ein moderner Bildschirm ungefähr darstellen?", answer: 16700000, unit: "Farben" },
  { question: "Wie viele Kilometer Unterseekabel liegen für das Internet unter den Weltmeeren ungefähr?", answer: 1400000, unit: "km" },
  { question: "Wie viele Jahre ist es her, dass die erste E-Mail verschickt wurde?", answer: 55, unit: "Jahre" },
  { question: "Wie viele Bauteile hat ein durchschnittliches Auto ungefähr?", answer: 30000, unit: "Bauteile" },
  { question: "Wie viele Kilometer Kabel stecken in einem Airbus A380 ungefähr?", answer: 500, unit: "km" },
  { question: "Wie viele Einzelteile hat eine Boeing 747 ungefähr?", answer: 6000000, unit: "Teile" },
  { question: "Wie viele Jahre ist es her, dass Edisons Glühbirne patentiert wurde?", answer: 147, unit: "Jahre" },
  { question: "Wie viele Patente hielt Thomas Edison insgesamt?", answer: 1093, unit: "Patente" },
  { question: "Wie viele Jahre ist es her, dass der erste Computer ENIAC gebaut wurde?", answer: 80, unit: "Jahre" },
  { question: "Wie viele Tonnen wog der erste Computer ENIAC?", answer: 27, unit: "Tonnen" },
  { question: "Wie viele Petaflops schafft ein moderner Supercomputer an der Spitze?", answer: 1000, unit: "Petaflops" },
  { question: "Wie viele Kilometer legt ein GPS-Signal von einem Satelliten bis zur Erde zurück ungefähr?", answer: 20200, unit: "km" },
  { question: "Wie viele Satelliten sind für das GPS-System im Einsatz?", answer: 31, unit: "Satelliten" },
  { question: "Wie viele Jahre ist es her, dass die erste SMS verschickt wurde?", answer: 33, unit: "Jahre" },
  { question: "Wie viele SMS wurden weltweit am Höhepunkt des SMS-Booms täglich verschickt?", answer: 20000000000, unit: "SMS" },
  { question: "Wie viele Fotos werden weltweit pro Tag geschossen ungefähr?", answer: 5000000000, unit: "Fotos" },
  { question: "Wie viele Exabyte an Daten werden weltweit pro Tag erzeugt ungefähr?", answer: 400, unit: "Exabyte" },
  { question: "Wie viele Jahre hält eine durchschnittliche Autobatterie?", answer: 5, unit: "Jahre" },
  { question: "Wie viele Kilometer Reichweite hat ein modernes Elektroauto im Schnitt pro Akkuladung?", answer: 400, unit: "km" },
  { question: "Wie viele Stunden dauert eine volle Ladung eines Elektroautos an der Haushaltssteckdose ungefähr?", answer: 10, unit: "Stunden" },
  { question: "Wie viele bewegliche Teile hat eine mechanische Armbanduhr ungefähr?", answer: 130, unit: "Teile" },
  { question: "Wie viele Jahre ist es her, dass der erste 3D-Drucker erfunden wurde?", answer: 42, unit: "Jahre" },
  { question: "Wie viele Grad Celsius erreicht die Spitze einer Rakete beim Wiedereintritt in die Atmosphäre?", answer: 1650, unit: "°C" },
  { question: "Wie viele PS hat ein moderner Formel-1-Motor ungefähr?", answer: 1000, unit: "PS" },
  { question: "Wie viele Tasten hat eine Standard-Computertastatur im QWERTZ-Layout?", answer: 105, unit: "Tasten" },
  { question: "Wie viele Megapixel hat eine typische Smartphone-Hauptkamera heute ungefähr?", answer: 50, unit: "Megapixel" },
  { question: "Wie viele Stunden Akkulaufzeit hat ein modernes Smartphone im Schnitt bei normaler Nutzung?", answer: 15, unit: "Stunden" },
  { question: "Wie viele Apps hat ein durchschnittlicher Smartphone-Nutzer installiert?", answer: 80, unit: "Apps" },
  { question: "Wie viele Zeichen passen in eine klassische SMS maximal?", answer: 160, unit: "Zeichen" },
  { question: "Wie viele Farben kann das menschliche Auge theoretisch maximal unterscheiden?", answer: 10000000, unit: "Farben" },

  // Wirtschaft / Alltagszahlen
  { question: "Wie viele Euro-Banknoten sind aktuell im Euroraum ungefähr im Umlauf?", answer: 30000000000, unit: "Banknoten" },
  { question: "Wie viele Mitarbeiter beschäftigt Amazon weltweit ungefähr?", answer: 1500000, unit: "Mitarbeiter" },
  { question: "Wie viele Filialen hat McDonald's weltweit ungefähr?", answer: 40000, unit: "Filialen" },
  { question: "Wie viele Tassen Kaffee werden weltweit täglich getrunken ungefähr?", answer: 2000000000, unit: "Tassen" },
  { question: "Wie viele Kilometer legt ein durchschnittliches Paket bei einem Versand innerhalb Deutschlands zurück?", answer: 300, unit: "km" },
  { question: "Wie viele Pakete verschickt DHL in Deutschland pro Jahr ungefähr?", answer: 1800000000, unit: "Pakete" },
  { question: "Wie viele Stunden arbeitet ein Vollzeitbeschäftigter in Deutschland durchschnittlich pro Woche?", answer: 38, unit: "Stunden" },
  { question: "Wie viele Urlaubstage stehen einem Arbeitnehmer in Deutschland mindestens gesetzlich zu?", answer: 20, unit: "Tage" },
  { question: "Wie viele Supermärkte gibt es in Deutschland ungefähr?", answer: 24000, unit: "Supermärkte" },
  { question: "Wie viel US-Dollar kostete das erste iPhone bei seiner Markteinführung 2007?", answer: 499, unit: "US-Dollar" },
  { question: "Wie viele Autos produziert Volkswagen weltweit pro Jahr ungefähr?", answer: 9000000, unit: "Autos" },
  { question: "Wie viele Mitarbeiter hat Volkswagen weltweit ungefähr?", answer: 680000, unit: "Mitarbeiter" },
  { question: "Wie viele Bäume werden weltweit jährlich für Papier gefällt ungefähr?", answer: 4000000000, unit: "Bäume" },
  { question: "Wie viele Plastiktüten verbraucht ein Mensch in Deutschland im Schnitt pro Jahr?", answer: 20, unit: "Plastiktüten" },
  { question: "Wie viele Liter Bier trinkt ein Deutscher im Schnitt pro Jahr?", answer: 88, unit: "Liter" },
  { question: "Wie viele Kilogramm Fleisch isst ein Deutscher im Schnitt pro Jahr?", answer: 52, unit: "kg" },
  { question: "Wie viele Euro gibt ein Deutscher im Schnitt monatlich für Lebensmittel aus?", answer: 400, unit: "Euro" },
  { question: "Wie viele Stunden verbringt ein Deutscher im Schnitt täglich mit dem Smartphone?", answer: 3, unit: "Stunden" },
  { question: "Wie viele Fernsehsender kann man in Deutschland über Kabel oder Satellit ungefähr empfangen?", answer: 100, unit: "Sender" },
  { question: "Wie viele Zeitungen werden in Deutschland täglich verkauft ungefähr?", answer: 10000000, unit: "Zeitungen" },
  { question: "Wie viele Autos sind in Deutschland aktuell zugelassen ungefähr?", answer: 49000000, unit: "Autos" },
  { question: "Wie viele Fahrräder gibt es in Deutschland ungefähr?", answer: 80000000, unit: "Fahrräder" },
  { question: "Wie viele Euro kostet eine durchschnittliche Hochzeit in Deutschland?", answer: 15000, unit: "Euro" },
  { question: "Wie viele Quadratmeter Wohnfläche hat eine durchschnittliche Wohnung in Deutschland?", answer: 92, unit: "m²" },
  { question: "Wie viele Euro verdient ein Arbeitnehmer in Deutschland im Schnitt brutto pro Monat?", answer: 4300, unit: "Euro" },
  { question: "Wie viele Unternehmen werden in Deutschland jährlich neu gegründet ungefähr?", answer: 600000, unit: "Unternehmen" },
  { question: "Wie viele Euro gibt ein Deutscher im Schnitt für Weihnachtsgeschenke pro Jahr aus?", answer: 500, unit: "Euro" },
  { question: "Wie viele Kilometer pendelt ein Berufstätiger in Deutschland im Schnitt einfach zur Arbeit?", answer: 17, unit: "km" },
  { question: "Wie viele Tonnen Lebensmittel werden in Deutschland jährlich weggeworfen?", answer: 11000000, unit: "Tonnen" },

  // Essen & Trinken
  { question: "Wie viele Kalorien hat ein durchschnittlicher Cheeseburger?", answer: 300, unit: "kcal" },
  { question: "Wie viele Kaffeebohnen braucht man für eine Tasse Espresso?", answer: 60, unit: "Bohnen" },
  { question: "Wie viele Käsesorten gibt es in Frankreich ungefähr?", answer: 1200, unit: "Käsesorten" },
  { question: "Wie viele Pizzen werden weltweit täglich gegessen ungefähr?", answer: 5000000, unit: "Pizzen" },
  { question: "Wie viele Kalorien hat eine Tafel Vollmilchschokolade mit 100 Gramm?", answer: 530, unit: "kcal" },
  { question: "Wie viele Kirschen wachsen an einem ausgewachsenen Kirschbaum pro Jahr ungefähr?", answer: 7000, unit: "Kirschen" },
  { question: "Wie viele Liter Milch gibt eine Kuh im Schnitt pro Jahr?", answer: 8000, unit: "Liter" },
  { question: "Wie viele Liter Wasser braucht man, um 1 Kilogramm Rindfleisch zu produzieren?", answer: 15000, unit: "Liter" },
  { question: "Wie viele Liter Wasser braucht man, um 1 Kilogramm Kaffee zu produzieren?", answer: 18900, unit: "Liter" },
  { question: "Wie viele Kilogramm Schokolade isst ein Deutscher im Schnitt pro Jahr?", answer: 9, unit: "kg" },
  { question: "Wie viele Tonnen Tomaten werden weltweit pro Jahr angebaut?", answer: 180000000, unit: "Tonnen" },
  { question: "Wie viele Kilogramm Kartoffeln isst ein Deutscher im Schnitt pro Jahr?", answer: 58, unit: "kg" },
  { question: "Wie viele Apfelsorten gibt es weltweit ungefähr?", answer: 7500, unit: "Apfelsorten" },
  { question: "Wie viele Kalorien hat ein Glas Vollmilch mit 250 Millilitern?", answer: 130, unit: "kcal" },
  { question: "Wie viele Gramm Zucker stecken in einer Dose Cola mit 330 Millilitern?", answer: 35, unit: "g" },
  { question: "Wie viele Anbauländer für Kaffee gibt es weltweit ungefähr?", answer: 60, unit: "Länder" },
  { question: "Wie viele Trauben braucht man für eine Flasche Wein?", answer: 600, unit: "Trauben" },
  { question: "In wie vielen Ländern wird kommerziell Wein angebaut?", answer: 70, unit: "Länder" },
  { question: "Wie viele Liter Wein trinkt ein Deutscher im Schnitt pro Jahr?", answer: 20, unit: "Liter" },
  { question: "Wie viele Gewürze umfasst eine klassische Curry-Gewürzmischung ungefähr?", answer: 10, unit: "Gewürze" },
  { question: "Wie viele Chili-Sorten gibt es weltweit ungefähr?", answer: 4000, unit: "Chili-Sorten" },
  { question: "Wie viele Millionen Scoville-Einheiten hat die schärfste Chilisorte der Welt ungefähr?", answer: 2, unit: "Mio. Scoville" },
  { question: "Wie viele Eissorten hat ein großer Eishersteller wie Ben & Jerry's ungefähr im Sortiment?", answer: 50, unit: "Eissorten" },
  { question: "Wie viele Liter Speiseeis isst ein Deutscher im Schnitt pro Jahr?", answer: 8, unit: "Liter" },
  { question: "Wie viele Brotsorten gibt es in Deutschland offiziell registriert?", answer: 3200, unit: "Brotsorten" },
  { question: "Wie viele Kilogramm Brot isst ein Deutscher im Schnitt pro Jahr?", answer: 55, unit: "kg" },
  { question: "Wie viele Bäckereien gibt es in Deutschland ungefähr?", answer: 9500, unit: "Bäckereien" },
  { question: "Wie viele Currywürste werden in Deutschland jährlich verkauft ungefähr?", answer: 800000000, unit: "Currywürste" },
  { question: "Wie viele Kalorien hat eine durchschnittliche Bratwurst?", answer: 300, unit: "kcal" },
  { question: "Wie viele Liter Bier passen in ein Standard-Bierfass in der Gastronomie?", answer: 50, unit: "Liter" },
  { question: "Wie viele Brauereien gibt es in Deutschland ungefähr?", answer: 1500, unit: "Brauereien" },
  { question: "Wie viele verschiedene Biersorten werden in Deutschland ungefähr gebraut?", answer: 6000, unit: "Biersorten" },
  { question: "Wie viele Kalorien hat eine mittelgroße Banane?", answer: 105, unit: "kcal" },
  { question: "Wie viele Kalorien hat ein Apfel im Schnitt?", answer: 80, unit: "kcal" },
  { question: "Wie viele Gramm wiegt ein durchschnittliches Hühnerei?", answer: 60, unit: "g" },
  { question: "Wie viele Eier isst ein Deutscher im Schnitt pro Jahr?", answer: 235, unit: "Eier" },
  { question: "Wie viele Liter Olivenöl produziert ein durchschnittlicher Olivenbaum pro Jahr?", answer: 5, unit: "Liter" },
  { question: "Wie viele verschiedene Gewürze werden weltweit im Handel unterschieden ungefähr?", answer: 100, unit: "Gewürze" },
  { question: "Wie viele Kilogramm Nudeln isst ein Italiener im Schnitt pro Jahr?", answer: 23, unit: "kg" },

  // Sprache
  { question: "Wie viele Buchstaben hat das deutsche Alphabet inklusive Umlaute und ß?", answer: 30, unit: "Buchstaben" },
  { question: "Wie viele Wörter enthält der Duden ungefähr?", answer: 148000, unit: "Wörter" },
  { question: "Wie viele Wörter umfasst der aktive Wortschatz eines Erwachsenen durchschnittlich?", answer: 16000, unit: "Wörter" },
  { question: "Wie viele verschiedene Muttersprachen werden in Deutschland ungefähr gesprochen?", answer: 60, unit: "Sprachen" },
  { question: "Wie viele Buchstaben hat das längste Wort im englischen Wörterbuch ungefähr?", answer: 45, unit: "Buchstaben" },
  { question: "Wie viele grammatikalische Fälle hat die deutsche Sprache?", answer: 4, unit: "Fälle" },
  { question: "Wie viele Zeitformen gibt es im Deutschen?", answer: 6, unit: "Zeitformen" },
  { question: "Wie viele Menschen sprechen Mandarin-Chinesisch als Muttersprache weltweit ungefähr?", answer: 940000000, unit: "Menschen" },
  { question: "Wie viele Menschen sprechen weltweit Englisch als Mutter- oder Zweitsprache ungefähr?", answer: 1500000000, unit: "Menschen" },
  { question: "Wie viele Buchstaben hat das griechische Alphabet?", answer: 24, unit: "Buchstaben" },
  { question: "Wie viele Buchstaben hat das kyrillische Alphabet des Russischen?", answer: 33, unit: "Buchstaben" },
  { question: "Wie viele Zeichen umfasst das japanische Hiragana-Alphabet?", answer: 46, unit: "Zeichen" },
  { question: "Wie viele Schriftzeichen muss man ungefähr kennen, um eine chinesische Zeitung flüssig zu lesen?", answer: 3000, unit: "Schriftzeichen" },
  { question: "Wie viele Sprachen sterben weltweit schätzungsweise pro Jahr aus?", answer: 2, unit: "Sprachen" },
  { question: "Wie viele Wörter hat ein durchschnittlicher Roman ungefähr?", answer: 90000, unit: "Wörter" },
  { question: "Wie viele Seiten hat ein durchschnittliches Taschenbuch?", answer: 300, unit: "Seiten" },
  { question: "Wie viele Emojis gibt es aktuell im Unicode-Standard ungefähr?", answer: 3700, unit: "Emojis" },
  { question: "Wie viele Wörter enthält ein durchschnittlicher deutscher Zeitungsartikel?", answer: 600, unit: "Wörter" },
  { question: "Wie viele offizielle Amtssprachen hat die Europäische Union?", answer: 24, unit: "Amtssprachen" },
  { question: "Wie viele Buchstaben hat ein deutsches Wort im Schnitt?", answer: 6, unit: "Buchstaben" },

  // Natur / Wetter / Klima
  { question: "Wie viele Grad Celsius wurde die höchste je gemessene Lufttemperatur auf der Erde?", answer: 56, unit: "°C" },
  { question: "Wie viele Grad Celsius wurde die tiefste je gemessene Temperatur auf der Erde (negativ)?", answer: -89, unit: "°C" },
  { question: "Wie viele km/h erreichte der stärkste je gemessene Windstoß auf der Erde?", answer: 408, unit: "km/h" },
  { question: "Wie viele Blitze schlagen weltweit pro Sekunde ungefähr ein?", answer: 44, unit: "Blitze" },
  { question: "Wie viele Grad Celsius heiß kann ein Blitz werden?", answer: 30000, unit: "°C" },
  { question: "Wie viele Liter Regen fallen bei einem starken Gewitter pro Quadratmeter?", answer: 30, unit: "Liter" },
  { question: "Wie viele Baumarten gibt es weltweit ungefähr?", answer: 73000, unit: "Baumarten" },
  { question: "Wie alt kann ein Mammutbaum (Sequoia) werden?", answer: 3000, unit: "Jahre" },
  { question: "Wie hoch kann ein Mammutbaum (Sequoia) werden?", answer: 95, unit: "m" },
  { question: "Wie viele Bäume gibt es auf der Erde schätzungsweise?", answer: 3000000000000, unit: "Bäume" },
  { question: "Wie viele Quadratkilometer Regenwald verschwinden weltweit jährlich ungefähr?", answer: 100000, unit: "km²" },
  { question: "Wie viel Prozent der Erdoberfläche ist von Ozeanen bedeckt?", answer: 71, unit: "%" },
  { question: "Wie tief ist der Ozean im Durchschnitt?", answer: 3700, unit: "m" },
  { question: "Wie viele Vulkane sind auf der Erde aktuell ungefähr aktiv?", answer: 1500, unit: "Vulkane" },
  { question: "Wie viele Erdbeben werden weltweit jährlich registriert, auch sehr schwache?", answer: 500000, unit: "Erdbeben" },
  { question: "Wie viel Prozent des Wassers auf der Erde ist Süßwasser?", answer: 3, unit: "%" },
  { question: "Wie viele Meter hoch können große Tsunami-Wellen an der Küste werden?", answer: 30, unit: "m" },
  { question: "Wie schnell breitet sich ein Tsunami auf offener See aus?", answer: 800, unit: "km/h" },
  { question: "Wie viele km/h kann eine fallende Schneeflocke ungefähr erreichen?", answer: 5, unit: "km/h" },
  { question: "Wie viele Kilometer dick ist die Erdatmosphäre ungefähr bis zur Kármán-Linie?", answer: 100, unit: "km" },
  { question: "Wie viele Prozent der Luft in der Erdatmosphäre bestehen aus Sauerstoff?", answer: 21, unit: "%" },
  { question: "Wie viele Prozent der Luft in der Erdatmosphäre bestehen aus Stickstoff?", answer: 78, unit: "%" },
  { question: "Wie viele Kilometer dick ist die Erdkruste unter den Kontinenten im Schnitt?", answer: 35, unit: "km" },
  { question: "Wie heiß ist der Erdkern im Zentrum ungefähr?", answer: 6000, unit: "°C" },
  { question: "Wie viele Kilometer tief liegt der Erdkern unter der Oberfläche?", answer: 6371, unit: "km" },
  { question: "Wie viele Regentage hat Deutschland im Schnitt pro Jahr?", answer: 180, unit: "Tage" },
  { question: "Wie viele Liter Regen fallen in Deutschland im Schnitt pro Quadratmeter und Jahr?", answer: 800, unit: "Liter" },
  { question: "Wie viele Sonnenstunden hat Deutschland im Schnitt pro Jahr?", answer: 1600, unit: "Stunden" },
  { question: "Wie viele Wirbelstürme entstehen im Nordatlantik im Schnitt pro Jahr?", answer: 14, unit: "Stürme" },
  { question: "Wie schnell können die Winde in einem Tornado der höchsten Kategorie werden?", answer: 500, unit: "km/h" },
  { question: "Wie viele Tornados werden in den USA jährlich registriert ungefähr?", answer: 1200, unit: "Tornados" },
  { question: "Wie viele Gletscher gibt es weltweit ungefähr?", answer: 200000, unit: "Gletscher" },
  { question: "Wie viel Prozent des Süßwassers der Erde ist in Gletschern und Eis gebunden?", answer: 68, unit: "%" },
  { question: "Wie dick ist das Eis in der Antarktis im Schnitt?", answer: 2000, unit: "m" },
  { question: "Wie viele Kilogramm CO2 nimmt ein ausgewachsener Baum im Schnitt pro Jahr auf?", answer: 22, unit: "kg" },
  { question: "Wie viele Liter Wasser verdunstet ein großer Laubbaum an einem heißen Sommertag?", answer: 400, unit: "Liter" },
  { question: "Wie viele Jahre dauert es, bis aus einem gefallenen Baum wieder Humus wird?", answer: 10, unit: "Jahre" },
  { question: "Wie hoch war der höchste je gemessene Wasserstand einer Sturmflut an der Nordseeküste?", answer: 5, unit: "m" },
  { question: "Wie viele Pflanzenarten gibt es im Amazonas-Regenwald ungefähr?", answer: 40000, unit: "Pflanzenarten" },
  { question: "Wie viele Tierarten leben im Amazonas-Regenwald schätzungsweise?", answer: 400000, unit: "Tierarten" },

  // Verkehr / Fahrzeuge
  { question: "Wie viele Autos werden weltweit pro Jahr ungefähr produziert?", answer: 90000000, unit: "Autos" },
  { question: "Wie viele Kilometer Autobahn gibt es in Deutschland?", answer: 13000, unit: "km" },
  { question: "Wie viele Kilometer Schienennetz hat die Deutsche Bahn ungefähr?", answer: 33000, unit: "km" },
  { question: "Wie schnell fährt der ICE maximal?", answer: 300, unit: "km/h" },
  { question: "Wie schnell fährt der schnellste Zug der Welt, der Shanghai Transrapid?", answer: 431, unit: "km/h" },
  { question: "Wie viele Passagiere transportiert ein Airbus A380 maximal?", answer: 850, unit: "Passagiere" },
  { question: "Wie schnell fliegt ein Verkehrsflugzeug im Reiseflug durchschnittlich?", answer: 900, unit: "km/h" },
  { question: "Wie hoch fliegt ein Verkehrsflugzeug im Reiseflug normalerweise?", answer: 10000, unit: "m" },
  { question: "Wie viele Flugzeuge sind weltweit gleichzeitig durchschnittlich in der Luft?", answer: 9000, unit: "Flugzeuge" },
  { question: "Wie viele Flughäfen gibt es weltweit ungefähr?", answer: 41000, unit: "Flughäfen" },
  { question: "Wie viele Passagiere fliegen weltweit pro Jahr ungefähr?", answer: 4500000000, unit: "Passagiere" },
  { question: "Wie viele Container passen auf ein großes Containerschiff?", answer: 24000, unit: "Container" },
  { question: "Wie lang sind die größten Containerschiffe der Welt?", answer: 400, unit: "m" },
  { question: "Wie viele Kilometer legt ein durchschnittliches Auto in Deutschland pro Jahr zurück?", answer: 13000, unit: "km" },
  { question: "Wie viele Fahrräder werden in Deutschland jährlich ungefähr verkauft?", answer: 4000000, unit: "Fahrräder" },
  { question: "Wie viele Kilometer Radweg gibt es in Deutschland ungefähr?", answer: 200000, unit: "km" },
  { question: "Wie viele PS hatte das erste Auto der Welt, der Benz Patent-Motorwagen?", answer: 1, unit: "PS" },
  { question: "Wie schnell fuhr das erste Auto der Welt maximal?", answer: 16, unit: "km/h" },
  { question: "Wie viele Autos sind pro 1000 Einwohner in Deutschland zugelassen?", answer: 580, unit: "Autos" },
  { question: "Wie viele Kilometer lang ist die Transsibirische Eisenbahn?", answer: 9289, unit: "km" },
  { question: "Wie viele Zeitzonen durchquert die Transsibirische Eisenbahn?", answer: 7, unit: "Zeitzonen" },
  { question: "Wie viele Tage dauert eine komplette Fahrt mit der Transsibirischen Eisenbahn?", answer: 7, unit: "Tage" },
  { question: "Wie viele Kilometer legt ein Verkehrsflugzeug im Laufe seiner Betriebszeit ungefähr zurück?", answer: 100000000, unit: "km" },
  { question: "Wie schnell kann ein modernes Serien-Motorrad maximal fahren?", answer: 300, unit: "km/h" },
  { question: "Wie viele Kilogramm wiegt ein leeres Verkehrsflugzeug wie eine Boeing 747?", answer: 180000, unit: "kg" },
  { question: "Wie viele Liter Kerosin verbraucht ein Airbus A380 pro Flugstunde ungefähr?", answer: 12000, unit: "Liter" },
  { question: "Wie viele Fahrgäste befördert die New Yorker U-Bahn täglich ungefähr?", answer: 4000000, unit: "Fahrgäste" },
  { question: "Wie viele Kilometer Streckennetz hat die Londoner U-Bahn?", answer: 400, unit: "km" },
  { question: "Wie viele Stationen hat die Londoner U-Bahn?", answer: 272, unit: "Stationen" },
  { question: "Wie viele Kilometer lang ist die Panamericana, die längste Straße der Welt?", answer: 30000, unit: "km" },
  { question: "Wie viele Millionen Standardcontainer (TEU) werden weltweit jährlich verschifft ungefähr?", answer: 800000000, unit: "TEU" },
  { question: "Wie viele Kilometer Streckennetz hat die Pariser Metro?", answer: 220, unit: "km" },
  { question: "Wie viele Aufzüge gibt es weltweit ungefähr?", answer: 20000000, unit: "Aufzüge" },
  { question: "Wie viele Menschen werden weltweit täglich mit Aufzügen befördert?", answer: 1000000000, unit: "Menschen" },
  { question: "Wie viele Kilometer lang ist die längste Eisenbahnbrücke der Welt?", answer: 165, unit: "km" },

  // Musik / Film
  { question: "Wie viele Minuten dauert ein durchschnittlicher Kinofilm?", answer: 110, unit: "Minuten" },
  { question: "Wie viele Filme umfasst die Star-Wars-Hauptreihe von Episode 1 bis 9?", answer: 9, unit: "Filme" },
  { question: "Wie viele Harry-Potter-Filme gibt es insgesamt?", answer: 8, unit: "Filme" },
  { question: "Wie viele Minuten dauert die Extended Edition von 'Die Rückkehr des Königs'?", answer: 263, unit: "Minuten" },
  { question: "Wie viele Marvel-Filme des MCU sind bis 2024 ungefähr erschienen?", answer: 33, unit: "Filme" },
  { question: "Wie viele Minuten dauert ein durchschnittlicher Popsong?", answer: 3, unit: "Minuten" },
  { question: "Wie viele Tasten hat ein klassisches Klavier?", answer: 88, unit: "Tasten" },
  { question: "Wie viele Saiten hat eine klassische Gitarre?", answer: 6, unit: "Saiten" },
  { question: "Wie viele Saiten hat eine Violine?", answer: 4, unit: "Saiten" },
  { question: "Wie viele Musiker spielen in einem klassischen Sinfonieorchester ungefähr?", answer: 90, unit: "Musiker" },
  { question: "Wie viele Studioalben hat die Band Metallica bisher veröffentlicht?", answer: 11, unit: "Alben" },
  { question: "Wie viele Wochen stand der langlebigste Nummer-1-Song ununterbrochen an der Spitze der Billboard-Charts?", answer: 19, unit: "Wochen" },
  { question: "Wie viele Kinosäle hat ein durchschnittliches Multiplex-Kino?", answer: 10, unit: "Kinosäle" },
  { question: "Wie viele Menschen passen in die größten Konzertarenen der Welt ungefähr?", answer: 20000, unit: "Menschen" },
  { question: "Wie viele Folgen hat die Serie 'Die Simpsons' insgesamt ungefähr?", answer: 770, unit: "Folgen" },
  { question: "Wie viele Staffeln hat die Serie 'Game of Thrones'?", answer: 8, unit: "Staffeln" },
  { question: "Wie viele Minuten dauert die durchschnittliche Folge einer Netflix-Serie?", answer: 45, unit: "Minuten" },
  { question: "In wie viele Sprachen wurde der Film 'Titanic' von 1997 ungefähr synchronisiert?", answer: 30, unit: "Sprachen" },
  { question: "Wie viele Oscar-Nominierungen erhielt der Film 'La La Land'?", answer: 14, unit: "Nominierungen" },
  { question: "Wie viele Kameras werden bei den Dreharbeiten eines großen Hollywood-Blockbusters im Schnitt eingesetzt?", answer: 5, unit: "Kameras" },
  { question: "Wie viele Jahre dauerte die gesamte Produktion der 'Herr der Ringe'-Trilogie?", answer: 8, unit: "Jahre" },
  { question: "Wie viele Bücher umfasst die Harry-Potter-Buchreihe?", answer: 7, unit: "Bücher" },
  { question: "Wie viele Wörter hat der längste Harry-Potter-Band, 'Orden des Phönix'?", answer: 257000, unit: "Wörter" },
  { question: "Wie viele Tonarten (Dur) gibt es in der westlichen Musik?", answer: 12, unit: "Tonarten" },
  { question: "Wie viele Grammy-Awards hat Beyoncé bisher insgesamt gewonnen?", answer: 32, unit: "Grammys" },
  { question: "Wie viele Millionen US-Dollar spielte der Film 'Avatar' weltweit an den Kinokassen ein?", answer: 2900000000, unit: "US-Dollar" },
  { question: "Wie viele Episoden hatte die erste Staffel von 'Friends'?", answer: 24, unit: "Episoden" },
  { question: "Wie viele Jahre lief die Serie 'Friends' insgesamt?", answer: 10, unit: "Jahre" },
  { question: "Wie viele Pfeifen hat eine große Kirchenorgel ungefähr?", answer: 5000, unit: "Pfeifen" },

  // Vermischtes
  { question: "Wie viele Zeitzonen gibt es auf der Erde insgesamt?", answer: 24, unit: "Zeitzonen" },
  { question: "Wie viele Farben hat ein Regenbogen klassischerweise?", answer: 7, unit: "Farben" },
  { question: "Wie viele Fünfecke hat das klassische Muster eines Fußballs?", answer: 12, unit: "Fünfecke" },
  { question: "Wie viele Farben hat ein klassischer Zauberwürfel?", answer: 6, unit: "Farben" },
  { question: "Wie viele einzelne bewegliche Steinchen hat ein 3x3 Zauberwürfel?", answer: 26, unit: "Steinchen" },
  { question: "Wie viele Steine hat ein klassisches Doppel-6-Dominospiel?", answer: 28, unit: "Steine" },
  { question: "Wie viele Karten hat ein klassisches Skatblatt?", answer: 32, unit: "Karten" },
  { question: "Wie viele Karten hat ein klassisches Pokerblatt ohne Joker?", answer: 52, unit: "Karten" },
  { question: "Wie viele Felder hat ein Schachbrett?", answer: 64, unit: "Felder" },
  { question: "Wie viele Figuren hat jede Seite beim Schach zu Beginn?", answer: 16, unit: "Figuren" },
  { question: "Wie viele Felder hat ein Monopoly-Spielbrett?", answer: 40, unit: "Felder" },
  { question: "Wie viele Felder hat der Rundweg bei 'Mensch ärgere dich nicht'?", answer: 40, unit: "Felder" },
  { question: "Wie viele Seiten hat ein klassischer Würfel?", answer: 6, unit: "Seiten" },
  { question: "Wie viele Ringe hat das Olympische Symbol?", answer: 5, unit: "Ringe" },
  { question: "Wie viele Sterne hat die Flagge der Europäischen Union?", answer: 12, unit: "Sterne" },
  { question: "Wie viele Sterne hat die Flagge der USA?", answer: 50, unit: "Sterne" },
  { question: "Wie viele Streifen hat die Flagge der USA?", answer: 13, unit: "Streifen" },
  { question: "Wie viele Zeitzonen umfassen die USA inklusive Alaska und Hawaii?", answer: 6, unit: "Zeitzonen" },
  { question: "Wie viele Bundesstaaten haben die USA?", answer: 50, unit: "Bundesstaaten" },
  { question: "Wie viele Kantone hat die Schweiz?", answer: 26, unit: "Kantone" },
  { question: "Wie viele Mitgliedsstaaten hat die Europäische Union?", answer: 27, unit: "Mitgliedsstaaten" },
  { question: "Wie viele Mitgliedsländer hat die UNO?", answer: 193, unit: "Mitgliedsländer" },
  { question: "Wie viele Felder hat ein klassisches Bingo-Spielfeld?", answer: 25, unit: "Felder" },
  { question: "Wie viele Grifflöcher hat eine klassische Blockflöte?", answer: 8, unit: "Löcher" },
  { question: "Wie viele Saiten hat eine Konzertharfe im Schnitt?", answer: 47, unit: "Saiten" },
  { question: "Wie viele Grundfarben hat ein klassisches Uno-Kartenspiel?", answer: 4, unit: "Farben" },
  { question: "Wie viele Karten hat ein Uno-Kartenspiel insgesamt?", answer: 108, unit: "Karten" },
  { question: "Wie viele Teile hat ein klassisches Puzzle mittlerer Größe für Erwachsene oft?", answer: 1000, unit: "Teile" },
  { question: "Wie viele Steine hat das größte offizielle Lego-Set, das Lego-Titanic-Modell?", answer: 11695, unit: "Steine" },
  { question: "Wie viele Lego-Steine werden weltweit pro Jahr produziert ungefähr?", answer: 40000000000, unit: "Legosteine" },
  { question: "Wie viele Meter tief ist das tiefste von Menschen gegrabene Loch, die Kola-Bohrung?", answer: 12262, unit: "m" },
  { question: "Wie viele Stockwerke hat das höchste Gebäude Deutschlands, der Commerzbank Tower?", answer: 56, unit: "Stockwerke" },
  { question: "Wie hoch ist der Commerzbank Tower in Frankfurt?", answer: 259, unit: "m" },
  { question: "Wie viele Fenster hat der Burj Khalifa, das höchste Gebäude der Welt, ungefähr?", answer: 24000, unit: "Fenster" },
  { question: "Wie viele Aufzüge hat der Burj Khalifa?", answer: 57, unit: "Aufzüge" },
  { question: "Wie viele Etagen hat der Burj Khalifa?", answer: 163, unit: "Etagen" },
  { question: "Wie viele Kilometer lang ist die längste Standseilbahn der Welt?", answer: 12, unit: "km" },
  { question: "Wie viele Achterbahnen hat der größte Freizeitpark der Welt, Cedar Point, ungefähr?", answer: 17, unit: "Achterbahnen" },
  { question: "Wie schnell wird die schnellste Achterbahn der Welt, die Formula Rossa?", answer: 240, unit: "km/h" },
  { question: "Wie hoch ist die höchste Achterbahn der Welt, Kingda Ka?", answer: 139, unit: "m" },
];

export function pickQuestion(exclude: Set<string> = new Set()): GuessItQuestion {
  let pool = QUESTIONS.filter((q) => !exclude.has(q.question));
  if (pool.length === 0) {
    exclude.clear();
    pool = QUESTIONS;
  }
  return pool[Math.floor(Math.random() * pool.length)];
}
