import { wordsMatch } from "../gameUtils/fuzzyMatch.js";
import type { Player } from "../types.js";

const CATEGORIES = [
  "Stadt",
  "Land",
  "Fluss",
  "Vorname",
  "Tier",
  "Beruf",
  "Farbe",
  "Automarke",
  "Obst oder Gemüse",
  "Filmtitel",
  "Pflanze",
  "Sportart",
  "Haustier",
  "Zootier",
  "Wildtier",
  "Meerestier",
  "Vogelart",
  "Insekt",
  "Fisch",
  "Reptil",
  "Raubtier",
  "Nutztier",
  "Zirkustier",
  "Dschungeltier",
  "Wüstentier",
  "Polartier",
  "Nagetier",
  "Zugvogel",
  "Greifvogel",
  "Schmetterlingsart",
  "Käferart",
  "Spinnentier",
  "Affenart",
  "Bärenart",
  "Katzenrasse",
  "Hunderasse",
  "Pferderasse",
  "Dinosaurier",
  "Fabelwesen",
  "Australisches Tier",
  "Afrikanisches Tier",
  "Tier im Zoo",
  "Tier im Wald",
  "Tier auf dem Bauernhof",
  "Tier im Meer",
  "Giftiges Tier",
  "Schnellstes Tier",
  "Größtes Tier",
  "Süßigkeit",
  "Fastfood",
  "Getränk",
  "Eissorte",
  "Pizzabelag",
  "Gewürz",
  "Käsesorte",
  "Wurstsorte",
  "Brotsorte",
  "Nudelgericht",
  "Suppe",
  "Nachspeise",
  "Kuchensorte",
  "Schokoladensorte",
  "Chipssorte",
  "Frühstück",
  "Milchprodukt",
  "Fischgericht",
  "Fleischgericht",
  "Vegetarisches Gericht",
  "Getreidesorte",
  "Nusssorte",
  "Kräutersorte",
  "Alkoholisches Getränk",
  "Erfrischungsgetränk",
  "Heißgetränk",
  "Cocktail",
  "Snack",
  "Fastfood-Kette",
  "Restaurantkette",
  "Grillgut",
  "Salat",
  "Dessert",
  "Backware",
  "Brotaufstrich",
  "Marmeladensorte",
  "Limonadensorte",
  "Biermarke",
  "Weinsorte",
  "Trockenfrucht",
  "Gemüsesorte",
  "Obstsorte",
  "Pastagericht",
  "Suppeneinlage",
  "Frühstücksgetränk",
  "Fastfood-Beilage",
  "Grillsoße",
  "Eiscrememarke",
  "Kaugummisorte",
  "Bonbonsorte",
  "Hauptstadt",
  "Kontinent",
  "Bundesland",
  "Sehenswürdigkeit",
  "Insel",
  "Meer",
  "Gebirge",
  "Wüste",
  "Weltmeer",
  "Inselstaat",
  "Nachbarland Deutschlands",
  "Urlaubsland",
  "Urlaubsziel",
  "See",
  "Stadtteil",
  "Großstadt",
  "Deutsche Stadt",
  "Europäische Stadt",
  "Wahrzeichen",
  "Reiseziel",
  "Sprache",
  "Weltwunder",
  "Vulkan",
  "Berg",
  "Tal",
  "Kanal",
  "Fluss in Europa",
  "Land in Europa",
  "Land in Afrika",
  "Land in Asien",
  "Hauptstadt Europas",
  "Insel im Mittelmeer",
  "Skigebiet",
  "Deutsche Insel",
  "Deutscher Fluss",
  "Deutscher Berg",
  "Handwerksberuf",
  "Medizinischer Beruf",
  "Traumberuf",
  "Schulberuf",
  "Berufsbezeichnung",
  "Studienfach",
  "Ausbildungsberuf",
  "Bürojob",
  "Modeberuf",
  "Beruf im Krankenhaus",
  "Beruf auf dem Bauernhof",
  "Beruf in der Schule",
  "Handwerker",
  "Uniformberuf",
  "Kreativberuf",
  "Motorradmarke",
  "Fluggesellschaft",
  "Fahrradmarke",
  "Fahrzeugtyp",
  "LKW-Marke",
  "Sportwagenmarke",
  "Verkehrsmittel",
  "Reifenmarke",
  "Automodell",
  "Deutsche Automarke",
  "Japanische Automarke",
  "Elektroauto-Marke",
  "Baustellenfahrzeug",
  "Einsatzfahrzeug",
  "Fortbewegungsmittel",
  "Fußballverein",
  "Olympiadisziplin",
  "Wintersportart",
  "Sommersportart",
  "Ballsportart",
  "Kampfsportart",
  "Basketballteam",
  "Formel-1-Fahrer",
  "Tennisspieler",
  "Sportverein",
  "Turnübung",
  "Extremsportart",
  "Bundesligaverein",
  "Sportgerät",
  "Fußballnationalspieler",
  "Fußballposition",
  "Wassersportart",
  "Trendsportart",
  "Schulsportart",
  "Sportart mit Ball",
  "Sportart im Wasser",
  "Sportart im Schnee",
  "TV-Serie",
  "Comicfigur",
  "Superheld",
  "Videospiel",
  "Zeichentrickfigur",
  "Musikinstrument",
  "Band",
  "Musikgenre",
  "Schauspieler",
  "Sänger",
  "Disney-Figur",
  "Märchenfigur",
  "Zeichentrickserie",
  "Kinderserie",
  "Serienfigur",
  "Filmreihe",
  "Bösewicht",
  "Popstar",
  "Rapper",
  "Boygroup",
  "Talkshow",
  "Castingshow",
  "Videospielfigur",
  "Spielkonsole",
  "Brettspiel",
  "Kartenspiel",
  "Gesellschaftsspiel",
  "Kinderbuch",
  "Buchtitel",
  "Weihnachtsfilm",
  "Actionfilm",
  "Horrorfilm",
  "Komödie",
  "Animationsfilm",
  "Musical",
  "Tanzstil",
  "Radiosender",
  "Influencer",
  "Meme",
  "Kinofilm",
  "Zeichentrickfilm",
  "Disney-Film",
  "Netflix-Serie",
  "Fernsehshow",
  "Quizshow",
  "Kochshow",
  "Serienschurke",
  "Kinderfilm",
  "Actionheld",
  "Kleidungsstück",
  "Möbelstück",
  "Elektrogerät",
  "Schulfach",
  "Feiertag",
  "Haushaltsgerät",
  "Küchengerät",
  "Werkzeug",
  "Schulgegenstand",
  "Büroartikel",
  "Spielzeug",
  "Accessoire",
  "Schuhmarke",
  "Kleidungsmarke",
  "Parfummarke",
  "Kosmetikprodukt",
  "Reinigungsmittel",
  "Baumarktartikel",
  "Gartengerät",
  "Sportartikel",
  "Handymarke",
  "Elektronikmarke",
  "Computerspiel",
  "App",
  "Social-Media-Plattform",
  "Suchmaschine",
  "Betriebssystem",
  "Süßwarenmarke",
  "Supermarktkette",
  "Drogeriemarke",
  "Zeitschrift",
  "Fernsehsender",
  "Küchenutensil",
  "Badezimmerartikel",
  "Schmuckstück",
  "Frisur",
  "Möbelstück im Wohnzimmer",
  "Gegenstand im Schulranzen",
  "Gegenstand am Strand",
  "Gegenstand im Bad",
  "Gegenstand in der Küche",
  "Gegenstand im Büro",
  "Gegenstand im Kinderzimmer",
  "Baum",
  "Blume",
  "Wetterphänomen",
  "Jahreszeit",
  "Laubbaum",
  "Nadelbaum",
  "Obstbaum",
  "Zimmerpflanze",
  "Gartenpflanze",
  "Wildblume",
  "Naturphänomen",
  "Himmelskörper",
  "Sternbild",
  "Planet",
  "Edelstein",
  "Naturkatastrophe",
  "Frühlingsblume",
  "Herbstlaub-Farbe",
  "Nachname",
  "Jungenname",
  "Mädchenname",
  "Kosename",
  "Spitzname",
  "Prominame",
  "Königsname",
  "Hundename",
  "Katzenname",
  "Altmodischer Vorname",
  "Moderner Vorname",
  "Fest",
  "Volksfest",
  "Weihnachtsbrauch",
  "Osterbrauch",
  "Geburtstagsgeschenk",
  "Hochzeitsgeschenk",
  "Weihnachtsgeschenk",
  "Weihnachtslied",
  "Kinderlied",
  "Volkslied",
  "Feiertagsessen",
  "Grillparty-Essen",
  "Faschingskostüm",
  "Karnevalskostüm",
  "Silvesterbrauch",
  "Adventsbrauch",
  "Geburtstagsspiel",
  "Traumurlaub",
  "Traumauto",
  "Kunstrichtung",
  "Maler",
  "Museum",
  "Comicverlag",
  "Kindersendung",
  "Gute-Nacht-Geschichte",
  "Märchen",
  "Sagengestalt",
  "Monster",
  "Gespenst",
  "Campingausrüstung",
  "Strandutensil",
  "Wintersportausrüstung",
  "Skiort",
  "Deutscher Nationalpark",
  "EU-Land",
  "Weltmacht",
  "Planet im Sonnensystem",
  "Wochentag",
  "Monat",
  "Zahl",
  "Geometrische Form",
  "Pausenbrot-Belag",
  "Kindergeburtstag-Spiel",
  "Regentag-Beschäftigung",
  "Sommeraktivität",
  "Winteraktivität",
  "Hobby",
  "Freizeitbeschäftigung",
  "Musikfestival",
  "Weltstar",
  "Fußballstar",
  "Tennisstar",
  "Möbelstück im Schlafzimmer",
  "Deko-Artikel",
  "Gartenmöbel",
  "Kinderspielzeug",
  "Outdoor-Spielzeug",
  "Brettspielklassiker",
  "Kartenspielklassiker",
  "Kinderspiel",
  "Partyspiel",
  "Trinkspiel",
  "Puzzleart",
  "Wintermonat",
  "Sommermonat",
  "Getränk zum Frühstück",
  "Fruchtsaftsorte",
  "Teesorte",
  "Kaffeegetränk",
  "Milchshake-Geschmack",
  "Pudding-Geschmack",
  "Jogurtsorte",
  "Müslizutat",
  "Salatzutat",
  "Suppentopping",
  "Grillbeilage",
  "Pommes-Sauce",
  "Burgerbelag",
  "Sandwichbelag",
  "Pizzasorte",
  "Sushi-Sorte",
  "Asiatisches Gericht",
  "Italienisches Gericht",
  "Deutsches Gericht",
  "Fingerfood",
  "Partysnack",
  "Chipsgeschmack",
  "Eisbecher-Zutat",
  "Kuchenbelag",
  "Torte",
  "Plätzchensorte",
  "Weihnachtsgebäck",
  "Osterschokolade",
  "Halloween-Süßigkeit",
  "Kirmesessen",
  "Volksfestattraktion",
  "Freizeitpark",
  "Achterbahn",
  "Wasserpark-Attraktion",
  "Zirkusnummer",
  "Zirkusfigur",
  "Jahrmarktspiel",
  "Kindergarten-Spielzeug",
  "Sandkastenspielzeug",
  "Wasserspielzeug",
  "Gesellschaftsspiel für Kinder",
  "Fernsehquiz",
  "Gameshow",
  "Streamingdienst",
  "Kinokette",
  "Filmgenre",
  "Buchgenre",
  "Romanautor",
  "Kinderbuchfigur",
  "Fantasyfigur",
  "Videospielkonsole",
  "Handyspiel",
  "Onlinespiel",
  "Computerspielgenre",
  "Retro-Videospiel",
  "Brettspielfigur",
  "Schachfigur",
  "Kartenspielsymbol",
  "Würfelspiel",
  "Tierlaut",
  "Aquariumbewohner",
  "Terrarium-Tier",
  "Haustierzubehör",
  "Hundespielzeug",
  "Katzenspielzeug",
  "Vogelfutter",
  "Fischfutter",
  "Tierfutter",
  "Streichelzoo-Tier",
  "Bauernhoftier",
  "Waldtier",
  "Gebirgstier",
  "Ozeanbewohner",
  "Korallenriff-Bewohner",
  "Hai-Art",
  "Wal-Art",
  "Delfinart",
  "Vogel am Futterhaus",
  "Greifvogelart",
  "Eulenart",
  "Entenart",
  "Gänseart",
  "Hühnerrasse",
  "Kuhrasse",
  "Schafrasse",
  "Ziegenrasse",
  "Schweinerasse",
  "Kaninchenrasse",
  "Hamsterart",
  "Reptilienart",
  "Schlangenart",
  "Echsenart",
  "Schildkrötenart",
  "Fischart im Aquarium",
  "Süßwasserfisch",
  "Meeresfisch",
  "Muschelart",
  "Krebstier",
  "Spinnenart",
  "Bienenart",
  "Ameisenart",
  "Wespenart",
  "Libellenart",
  "Fliegenart",
  "Mückenart",
  "Wurmart",
  "Schneckenart",
  "Baumart im Wald",
  "Nadelbaumart",
  "Obstbaumsorte",
  "Apfelsorte",
  "Birnensorte",
  "Beerenart",
  "Zitrusfrucht",
  "Tropische Frucht",
  "Exotische Frucht",
  "Wintergemüse",
  "Sommergemüse",
  "Wurzelgemüse",
  "Blattgemüse",
  "Kohlsorte",
  "Salatsorte",
  "Pilzart",
  "Speisepilz",
  "Kartoffelgericht",
  "Reisgericht",
  "Getreideprodukt",
  "Mehlsorte",
  "Backzutat",
  "Kuchenzutat",
  "Eiscremezutat",
  "Milchsorte",
  "Käseart",
  "Wurstart",
  "Fleischsorte",
  "Fischgericht zum Grillen",
  "Grillfleisch",
  "Marinade",
  "Sauce",
  "Senfart",
  "Essigsorte",
  "Ölsorte",
  "Gewürzmischung",
  "Kräuter im Garten",
  "Küchenkraut",
  "Heilpflanze",
  "Giftpflanze",
  "Zimmerblume",
  "Balkonpflanze",
  "Gartenblume",
  "Frühlingsboten",
  "Herbstfrucht",
  "Winterobst",
  "Sommerfrucht",
  "Nationalpark",
  "Weltmetropole",
  "Millionenstadt",
  "Hafenstadt",
  "Deutsches Bundesland",
  "Deutsche Landeshauptstadt",
  "Alpenland",
  "Skandinavisches Land",
  "Baltisches Land",
  "Balkanland",
  "Asiatisches Land",
  "Südamerikanisches Land",
  "Afrikanisches Land",
  "Ozeanien-Insel",
  "Karibikinsel",
  "Mittelmeerinsel",
  "Nordseeinsel",
  "Ostseeinsel",
  "Fluss in Deutschland",
  "See in Deutschland",
  "Gebirge in Europa",
  "Weltmeer der Erde",
  "Wüste der Welt",
  "Regenwald",
  "Savanne",
  "Steppe",
  "Tundra",
  "Eiszeit-Tier",
  "Urzeittier",
  "Sagenwesen",
  "Fabelfigur",
  "Superheldenteam",
  "Marvel-Figur",
  "DC-Figur",
  "Videospielserie",
  "Fantasy-Kreatur",
  "Brettspielverlag",
  "Spielzeughersteller",
  "Legofigur",
  "Puppenmarke",
  "Actionfigur",
  "Kuscheltier",
  "Plüschtierart",
  "Ballspiel",
  "Rückschlagsport",
  "Wintersportgerät",
  "Sommersportgerät",
  "Turngerät",
  "Fitnessgerät",
  "Fitnessstudio-Übung",
  "Yoga-Übung",
  "Tanzsportart",
  "Kampfsportstil",
  "Wassersportgerät",
  "Angelgerät",
  "Campingzubehör",
  "Wanderausrüstung",
  "Skiausrüstung",
  "Snowboardmarke",
  "Sportbekleidung",
  "Sportschuhmarke",
  "Trikotfarbe",
  "Vereinsfarbe",
  "Nationalmannschaft",
  "Fußball-Weltmeister",
  "Basketballspieler",
  "Handballverein",
  "Volleyballverein",
  "Eishockeyverein",
  "Formel-1-Team",
  "Boxweltmeister",
  "Leichtathletik-Disziplin",
  "Schwimmstil",
  "Wintersport-Disziplin",
  "Olympiastadt",
  "Fußballstadion",
  "Sportzeitschrift",
  "Musikinstrument im Orchester",
  "Blasinstrument",
  "Streichinstrument",
  "Schlaginstrument",
  "Tasteninstrument",
  "Musikrichtung der 80er",
  "Musikrichtung der 90er",
  "Konzertort",
  "Festivalname",
  "Schlagerstar",
  "Volksmusik-Interpret",
  "Klassischer Komponist",
  "Theaterstück",
  "Zeichentrickklassiker",
  "Anime-Serie",
  "Anime-Figur",
  "Videospielheld",
  "Retro-Konsole",
  "Laptophersteller",
  "Software-Unternehmen",
  "Tech-Konzern",
  "Streaming-Anbieter",
  "Social-Media-App",
  "Messenger-App",
  "Online-Shop",
  "Modehersteller",
  "Sportartikelhersteller",
  "Kosmetikmarke",
  "Uhrenmarke",
  "Schmuckmarke",
  "Möbelhersteller",
  "Haushaltsgerätehersteller",
  "Waschmittelmarke",
  "Brauereimarke",
  "Kaffeemarke",
  "Teemarke",
  "Schulfach der Oberstufe",
  "Studiengang",
  "Universitätsstadt",
  "Museumsart",
  "Schlossname",
  "Burgname",
  "Weihnachtsdekoration",
  "Osterdekoration",
  "Halloween-Dekoration",
  "Geburtstagsdekoration",
  "Partydekoration",
  "Hochzeitsdekoration",
  "Feuerwerksart",
  "Neujahrsvorsatz",
  "Sommerferien-Aktivität",
  "Winterferien-Aktivität",
  "Herbstferien-Aktivität",
  "Regenschutz",
  "Sonnenschutz",
  "Strandspiel",
  "Poolspiel",
  "Gartenspiel",
  "Kinderspielplatzgerät",
  "Schulhofspiel",
  "Klassenzimmergegenstand",
  "Schreibutensil",
  "Bastelmaterial",
  "Malutensil",
  "Kunstmaterial",
  "Nähzubehör",
  "Werkzeugkisteninhalt",
  "Gartenwerkzeug",
  "Geschirrteil",
  "Besteckteil",
  "Trinkgefäß",
  "Tassenart",
];

export function pickCategory(exclude: Set<string> = new Set()): string {
  let pool = CATEGORIES.filter((c) => !exclude.has(c));
  if (pool.length === 0) {
    exclude.clear();
    pool = CATEGORIES;
  }
  return pool[Math.floor(Math.random() * pool.length)];
}

export type SlfStage = "writing" | "results" | "finished";

export interface InternalSlfGame {
  id: "stadtlandfluss";
  stage: SlfStage;
  round: number;
  totalRounds: number;
  category: string;
  usedCategories: Set<string>;
  words: Map<string, string>; // playerId -> raw submitted word, cleared each round
  scores: Map<string, number>; // playerId -> cumulative total
  lastRoundEntries: { playerId: string; word: string | null; points: number }[] | null;
}

/** `usedCategories` is owned by the caller (the room) and mutated in place, so
 * categories already seen in earlier playthroughs in this room stay excluded
 * here too — not just within this one 10-round game. */
export function startStadtLandFluss(
  connectedPlayerIds: string[],
  usedCategories: Set<string>
): InternalSlfGame | null {
  if (connectedPlayerIds.length < 2) return null;
  const category = pickCategory(usedCategories);
  usedCategories.add(category);
  return {
    id: "stadtlandfluss",
    stage: "writing",
    round: 1,
    totalRounds: 10,
    category,
    usedCategories,
    words: new Map(),
    scores: new Map(connectedPlayerIds.map((id) => [id, 0])),
    lastRoundEntries: null,
  };
}

export function submitWord(game: InternalSlfGame, playerId: string, word: string): boolean {
  if (game.stage !== "writing") return false;
  const trimmed = word.trim().slice(0, 40);
  if (!trimmed) return false;
  game.words.set(playerId, trimmed);
  return true;
}

export function allConnectedSubmitted(game: InternalSlfGame, players: Map<string, Player>): boolean {
  const connectedIds = [...players.values()].filter((p) => p.connected).map((p) => p.id);
  return connectedIds.length > 0 && connectedIds.every((id) => game.words.has(id));
}

function groupByMatch(entries: { playerId: string; word: string }[]): string[][] {
  const groups: { rep: string; ids: string[] }[] = [];
  for (const { playerId, word } of entries) {
    const existing = groups.find((g) => wordsMatch(word, g.rep));
    if (existing) existing.ids.push(playerId);
    else groups.push({ rep: word, ids: [playerId] });
  }
  return groups.map((g) => g.ids);
}

/** Scores the just-finished round (fuzzy-matched groups of 2+ get 10 points
 * each, a lone answer gets 0), adds it to cumulative totals, and moves the
 * game into "results". Call once `allConnectedSubmitted` is true. */
export function revealRound(game: InternalSlfGame, players: Map<string, Player>): void {
  const connectedIds = [...players.values()].filter((p) => p.connected).map((p) => p.id);
  const withWords = connectedIds
    .map((playerId) => ({ playerId, word: game.words.get(playerId) ?? null }))
    .filter((e): e is { playerId: string; word: string } => !!e.word);

  const groups = groupByMatch(withWords);
  const pointsByPlayer = new Map<string, number>();
  for (const group of groups) {
    const points = group.length >= 2 ? 10 : 0;
    for (const id of group) pointsByPlayer.set(id, points);
  }

  game.lastRoundEntries = connectedIds.map((playerId) => {
    const word = game.words.get(playerId) ?? null;
    const points = pointsByPlayer.get(playerId) ?? 0;
    game.scores.set(playerId, (game.scores.get(playerId) ?? 0) + points);
    return { playerId, word, points };
  });
  game.stage = "results";
}

/** Host-triggered: starts the next round, or moves to "finished" if the
 * round that was just revealed was the last one. */
export function nextSlfRound(game: InternalSlfGame): boolean {
  if (game.stage !== "results") return false;
  if (game.round >= game.totalRounds) {
    game.stage = "finished";
    return true;
  }
  game.round += 1;
  const category = pickCategory(game.usedCategories);
  game.usedCategories.add(category);
  game.category = category;
  game.words = new Map();
  game.lastRoundEntries = null;
  game.stage = "writing";
  return true;
}
