const QUESTIONS = [
  "Wer würde eher auf dem Mond landen, ohne es jemandem zu sagen?",
  "Wer würde eher versehentlich eine Hochzeit crashen?",
  "Wer würde eher Millionär und würde es niemandem erzählen?",
  "Wer würde eher mitten in der Nacht anrufen, um über Verschwörungstheorien zu reden?",
  "Wer würde eher ein Haustier heimlich mit nach Hause bringen?",
  "Wer würde eher bei einem Fluchtversuch aus dem Gefängnis als Erstes erwischt werden?",
  "Wer würde eher ihren Job kündigen, um Straßenmusiker zu werden?",
  "Wer würde eher in eine Fernsehshow eingeladen werden?",
  "Wer würde eher versehentlich ein Flugzeug verpassen, weil er/sie sich verlaufen hat?",
  "Wer würde eher ein ganzes Wochenende ohne Handy überleben?",
  "Wer würde eher auf einer einsamen Insel als Anführer enden?",
  "Wer würde eher aus Versehen zu einer falschen Beerdigung gehen?",
  "Wer würde eher spontan in ein anderes Land ziehen?",
  "Wer würde eher bei einem Quizshow-Auftritt alles falsch beantworten, aber trotzdem gewinnen?",
  "Wer würde eher ein Geheimnis am längsten für sich behalten?",
  "Wer würde eher versuchen, mit einem Wildtier Freundschaft zu schließen?",
  "Wer würde eher auf einer Party als Erstes tanzen?",
  "Wer würde eher berühmt werden, ohne es zu wollen?",
  "Wer würde eher bei einem Escape Room den Rätseln am längsten hinterherhinken?",
  "Wer würde eher versehentlich den falschen Chat für eine peinliche Nachricht nutzen?",
  "Wer würde eher aus Versehen den Wecker auf die falsche Uhrzeit stellen und einen wichtigen Termin verpassen?",
  "Wer würde eher mit einem Klamottenetikett noch dran den ganzen Tag herumlaufen?",
  "Wer würde eher in der Öffentlichkeit laut über einen eigenen Witz lachen, den niemand gehört hat?",
  "Wer würde eher versehentlich die Hose falsch herum anziehen und es erst mittags merken?",
  "Wer würde eher beim Winken jemand komplett Fremdes anwinken?",
  "Wer würde eher mit Essen zwischen den Zähnen ein ganzes Meeting überstehen?",
  "Wer würde eher aus Versehen eine Sprachnachricht an die falsche Person schicken?",
  "Wer würde eher beim Niesen etwas kaputt machen?",
  "Wer würde eher in der Umkleidekabine eines Geschäfts laut Selbstgespräche führen?",
  "Wer würde eher den eigenen Namen vergessen, wenn er/sie sich vorstellen soll?",
  "Wer würde eher mit zwei unterschiedlichen Schuhen aus dem Haus gehen?",
  "Wer würde eher beim Small Talk plötzlich komplett das Thema wechseln, weil ihm/ihr nichts mehr einfällt?",
  "Wer würde eher versehentlich in eine Glastür laufen?",
  "Wer würde eher beim Reden ständig den Namen der falschen Person benutzen?",
  "Wer würde eher in einem stillen Raum unfreiwillig laut lachen müssen?",
  "Wer würde eher eine Autotür zumachen, während der Schlüssel noch drinnen liegt?",
  "Wer würde eher beim Handshake komplett danebengreifen?",
  "Wer würde eher stundenlang mit offenem Hosenstall herumlaufen, ohne es zu merken?",
  "Wer würde eher in einer Videokonferenz vergessen, das Mikro stummzuschalten, und es peinlich merken?",
  "Wer würde eher versehentlich den Chef oder die Chefin duzen, obwohl man siezen sollte?",
  "Wer würde eher beim Bezahlen an der Kasse die Karte fünfmal falsch herum einstecken?",
  "Wer würde eher ein Treffen komplett verschlafen, weil der Wecker nicht losging?",
  "Wer würde eher beim Vorstellungsgespräch aus Nervosität den falschen Firmennamen sagen?",
  "Wer würde eher eine Glückwunschkarte mit den völlig falschen Worten unterschreiben?",
  "Wer würde eher im Supermarkt an der falschen Kasse anstehen, obwohl 'geschlossen' dransteht?",
  "Wer würde eher aus Versehen in ein fremdes Auto steigen, weil es genauso aussah wie das eigene?",
  "Wer würde eher beim Gähnen versehentlich jemandem ins Gesicht atmen?",
  "Wer würde eher den ganzen Tag mit Kaffeeflecken auf dem Hemd herumlaufen, ohne es zu bemerken?",
  "Wer würde eher jemandem aus Versehen 'Ich liebe dich' statt 'Tschüss' am Telefon sagen?",
  "Wer würde eher beim Fotografieren aus Versehen ins eigene Gesicht blitzen?",
  "Wer würde eher eine wichtige E-Mail an den gesamten Verteiler statt an eine Person schicken?",
  "Wer würde eher beim Treppensteigen stolpern und so tun, als wäre nichts gewesen?",
  "Wer würde eher im Fahrstuhl aus Versehen alle Knöpfe drücken?",
  "Wer würde eher mit vollem Mund ans Telefon gehen und trotzdem reden?",
  "Wer würde eher beim Anstoßen mit Sekt das Glas komplett verfehlen?",
  "Wer würde eher spontan einen Rucksack packen und ohne Plan losreisen?",
  "Wer würde eher in einem fremden Land die Landessprache nur durch Zeigen und Gesten lernen?",
  "Wer würde eher per Anhalter quer durch ein Land reisen?",
  "Wer würde eher am Ende eines Trips mehr Geld für Souvenirs als für Übernachtungen ausgeben?",
  "Wer würde eher in einer Großstadt hoffnungslos die Orientierung verlieren?",
  "Wer würde eher eine Nacht am Flughafen verbringen, weil der Anschlussflug verpasst wurde?",
  "Wer würde eher auf einer Weltreise das Rückflugticket verlieren?",
  "Wer würde eher als Erste/r in ein Straßenessen beißen, das komplett unbekannt ist?",
  "Wer würde eher eine Höhle erkunden, obwohl niemand weiß, wohin er/sie geht?",
  "Wer würde eher mit einem Zelt mitten im Nirgendwo campen, ohne Handyempfang?",
  "Wer würde eher versuchen, mit einem Boot einen Fluss hinunterzupaddeln, ohne je gepaddelt zu sein?",
  "Wer würde eher einen ganzen Roadtrip nur nach Bauchgefühl planen?",
  "Wer würde eher in den Bergen eine falsche Abzweigung nehmen und stundenlang wandern, bevor er/sie es merkt?",
  "Wer würde eher im Ausland versehentlich etwas völlig anderes bestellen, als er/sie eigentlich wollte?",
  "Wer würde eher einen Fallschirmsprung im letzten Moment doch noch wahr machen?",
  "Wer würde eher eine Nacht in einem Baumhaus mitten im Dschungel verbringen wollen?",
  "Wer würde eher bei einer Bergtour als Erste/r um eine Pause bitten?",
  "Wer würde eher versuchen, eine fremde Stadt komplett zu Fuß zu erkunden, statt öffentliche Verkehrsmittel zu nehmen?",
  "Wer würde eher spontan ein One-Way-Ticket in ein Land buchen, in dem er/sie niemanden kennt?",
  "Wer würde eher beim Camping das Zelt falsch herum aufbauen?",
  "Wer würde eher auf einer Insel stranden und als Erste/r versuchen, ein Floß zu bauen?",
  "Wer würde eher in einem fremden Land ein Fahrzeug mieten, ohne die Verkehrsregeln zu kennen?",
  "Wer würde eher eine ganze Städtereise verplanen und dann doch spontan alles über den Haufen werfen?",
  "Wer würde eher bei einer Wüstensafari die meiste Zeit nach Schatten suchen?",
  "Wer würde eher versuchen, mit einheimischen Tieren auf Safari Selfies zu machen?",
  "Wer würde eher in einer fremden Stadt ein Straßenschild fotografieren, statt nach dem Weg zu fragen?",
  "Wer würde eher bei starkem Wellengang trotzdem ins Meer springen?",
  "Wer würde eher versuchen, eine ganze Woche nur mit Handgepäck zu reisen?",
  "Wer würde eher auf einer Zugfahrt in die komplett falsche Richtung einsteigen?",
  "Wer würde eher bei einer Wanderung ohne Karte und nur nach Gefühl weitergehen?",
  "Wer würde eher versuchen, an einem einzigen Tag drei verschiedene Länder zu besuchen?",
  "Wer würde eher freiwillig in einer Jugendherberge im Achtbettzimmer übernachten?",
  "Wer würde eher bei einer Kreuzfahrt seekrank werden und es trotzdem niemandem sagen?",
  "Wer würde eher versuchen, per Autostopp bis zum Nordkap zu kommen?",
  "Wer würde eher in einer fremden Stadt ein Fahrrad leihen, obwohl er/sie seit Jahren nicht mehr gefahren ist?",
  "Wer würde eher den gesamten Lottogewinn innerhalb eines Monats ausgeben?",
  "Wer würde eher eine sichere Festanstellung kündigen, um ein eigenes Unternehmen zu gründen?",
  "Wer würde eher beim Gehaltsgespräch komplett die Nerven verlieren?",
  "Wer würde eher sein gesamtes Erspartes in eine verrückte Geschäftsidee stecken?",
  "Wer würde eher zum Chef oder zur Chefin befördert werden, ohne es kommen zu sehen?",
  "Wer würde eher versehentlich eine private Nachricht über den Firmen-Chat an alle Kollegen schicken?",
  "Wer würde eher in einer Besprechung einschlafen?",
  "Wer würde eher sein ganzes Taschengeld an einem einzigen Tag ausgeben?",
  "Wer würde eher einen Nebenjob als Clown annehmen, um Geld zu verdienen?",
  "Wer würde eher bei einer Gehaltsverhandlung mehr fordern, als er/sie sich eigentlich traut?",
  "Wer würde eher sein Erspartes für ein Investment ausgeben, von dem er/sie eigentlich nichts versteht?",
  "Wer würde eher freiwillig unbezahlte Überstunden machen, ohne zu murren?",
  "Wer würde eher einen Bewerbungstermin verschlafen?",
  "Wer würde eher als Erste/r im Team eine verrückte Idee vorschlagen, die tatsächlich funktioniert?",
  "Wer würde eher sein gesamtes Budget für ein einziges teures Hobby ausgeben?",
  "Wer würde eher versuchen, mit einem selbstgebauten Produkt reich zu werden?",
  "Wer würde eher im Büro heimlich Mittagsschlaf halten?",
  "Wer würde eher eine Gehaltserhöhung bekommen, ohne aktiv danach gefragt zu haben?",
  "Wer würde eher spontan kündigen, weil ihm/ihr der Job zu langweilig wird?",
  "Wer würde eher versuchen, mit Trinkgeld allein einen Monat zu überleben?",
  "Wer würde eher ein Vorstellungsgespräch im völlig falschen Outfit antreten?",
  "Wer würde eher sein Geld lieber in Erlebnisse als in Dinge investieren?",
  "Wer würde eher versehentlich die Gehaltsabrechnung von jemand anderem lesen und nichts sagen?",
  "Wer würde eher einen Kredit aufnehmen, um sich einen Traum sofort zu erfüllen?",
  "Wer würde eher bei der Steuererklärung komplett den Überblick verlieren?",
  "Wer würde eher freiwillig eine Nachtschicht übernehmen, weil er/sie das Geld dafür will?",
  "Wer würde eher versuchen, mit einem Nebenjob als Straßenkünstler durchzukommen?",
  "Wer würde eher ein Startup gründen, das niemand versteht, aber trotzdem erfolgreich wird?",
  "Wer würde eher am Monatsende immer knapp bei Kasse sein, egal wie viel er/sie verdient?",
  "Wer würde eher einen ganzen Bonus sofort verplanen, bevor er überhaupt ausgezahlt wurde?",
  "Wer würde eher versuchen, in einer Besprechung mitzureden, ohne das Thema wirklich zu kennen?",
  "Wer würde eher einen sicheren Job für ein riskantes Traumprojekt aufgeben?",
  "Wer würde eher als Erste/r im Büro die Kaffeekasse leerräumen und es zugeben?",
  "Wer würde eher ein Vorstellungsgespräch mit einer völlig falschen Firma verwechseln?",
  "Wer würde eher freiwillig die undankbarste Aufgabe im Team übernehmen?",
  "Wer würde eher bei einem ersten Date komplett den falschen Ort ansteuern?",
  "Wer würde eher aus Versehen den Namen des Ex oder der Ex bei einem neuen Date benutzen?",
  "Wer würde eher die Eltern des Partners oder der Partnerin beim ersten Treffen zum Lachen bringen?",
  "Wer würde eher einer besten Freundin oder einem besten Freund ein Geheimnis anvertrauen, das er/sie niemandem sonst erzählt hat?",
  "Wer würde eher bei einer Familienfeier ein völlig falsches Thema ansprechen?",
  "Wer würde eher einem Freund oder einer Freundin bei einem Umzug helfen, obwohl er/sie eigentlich keine Zeit hat?",
  "Wer würde eher versehentlich eine Überraschungsparty verraten?",
  "Wer würde eher bei einer Hochzeit als Trauzeuge oder Trauzeugin die Rede vergessen?",
  "Wer würde eher heimlich Kontakt zu einem Kindheitsfreund oder einer Kindheitsfreundin aufnehmen, nach Jahren der Funkstille?",
  "Wer würde eher in einer Beziehung als Erste/r 'Ich liebe dich' sagen?",
  "Wer würde eher die Geschwister als seine oder ihre besten Freunde bezeichnen?",
  "Wer würde eher bei einem Streit als Erste/r nachgeben, nur um Ruhe zu haben?",
  "Wer würde eher heimlich einen Heiratsantrag komplett vermasseln, aber trotzdem ein Ja bekommen?",
  "Wer würde eher einem Freund oder einer Freundin zuliebe einen Marathon mitlaufen, obwohl er/sie das hasst?",
  "Wer würde eher bei einem Blind Date sofort merken, dass es nicht passt, es aber nicht sagen?",
  "Wer würde eher die Familie mit einer spontanen Verlobung überraschen?",
  "Wer würde eher als Erste/r im Freundeskreis Kinder bekommen?",
  "Wer würde eher bei einem Elternabend für die eigenen Kinder komplett fehl am Platz wirken?",
  "Wer würde eher einer Freundschaft aus der Kindheit treu bleiben, egal wie weit man sich entfernt?",
  "Wer würde eher bei einer Verabredung viel zu früh erscheinen?",
  "Wer würde eher versuchen, die eigenen Eltern miteinander zu verkuppeln, nachdem sie sich getrennt haben?",
  "Wer würde eher heimlich eine Dating-App löschen und wieder installieren, ohne es jemandem zu sagen?",
  "Wer würde eher bei einem Beziehungsstreit die versöhnende Person in der Gruppe sein?",
  "Wer würde eher einem Familienmitglied zuliebe einen Umzug in eine andere Stadt in Kauf nehmen?",
  "Wer würde eher bei einer Verabredung das Gespräch komplett zum Stocken bringen?",
  "Wer würde eher heimlich für den Partner oder die Partnerin ein riesiges Geschenk planen und es tagelang geheim halten?",
  "Wer würde eher bei einem WG-Casting sofort den Vibe checken und Nein sagen?",
  "Wer würde eher als Erste/r bei einer Gruppenreise mit Freunden die Planung übernehmen?",
  "Wer würde eher einem entfernten Verwandten bei einer Familienfeier den Namen nicht mehr einfallen?",
  "Wer würde eher versuchen, mit den Schwiegereltern eine bessere Beziehung als mit den eigenen Eltern zu haben?",
  "Wer würde eher bei einem Date zugeben, dass er/sie schon vorher heimlich das Profil gestalkt hat?",
  "Wer würde eher einem Freund oder einer Freundin eine Standpauke halten, wenn es nötig ist?",
  "Wer würde eher versuchen, die ganze Familie zu einem gemeinsamen Urlaub zu überreden?",
  "Wer würde eher bei einer Trennung als Erste/r wieder auf ein Date gehen?",
  "Wer würde eher eine Freundschaft retten, die kurz vor dem Aus steht?",
  "Wer würde eher auf einer Party als Letzte/r gehen?",
  "Wer würde eher bei einem Trinkspiel als Erste/r aussteigen?",
  "Wer würde eher eine ganze Playlist für eine Party allein zusammenstellen?",
  "Wer würde eher auf einer Karaoke-Party ein Lied singen, das niemand kennt?",
  "Wer würde eher versuchen, eine ganze Party allein zu unterhalten?",
  "Wer würde eher bei einer Kostümparty das aufwendigste Kostüm tragen?",
  "Wer würde eher auf einer Feier ein Spiel vorschlagen, das dann alle mitreißt?",
  "Wer würde eher bei einer Party heimlich früher gehen, ohne sich zu verabschieden?",
  "Wer würde eher auf einer Hochzeit als Erste/r die Tanzfläche eröffnen?",
  "Wer würde eher bei einem Grillabend als Griller oder Grillerin einspringen, obwohl er/sie keine Ahnung hat?",
  "Wer würde eher versuchen, bei einem Quizabend das Team im Alleingang zu retten?",
  "Wer würde eher auf einer Party mit Fremden den ganzen Abend lang das interessanteste Gespräch führen?",
  "Wer würde eher versehentlich zwei Partys am selben Abend zusagen?",
  "Wer würde eher bei einem Gruppenfoto immer die Grimasse schneiden?",
  "Wer würde eher eine spontane Poolparty organisieren?",
  "Wer würde eher bei einem Wichteln das schlechteste Geschenk mitbringen?",
  "Wer würde eher versuchen, auf einer Feier ein Feuerwerk zu improvisieren?",
  "Wer würde eher bei einer Übernachtungsparty als Letzte/r einschlafen?",
  "Wer würde eher eine Themenparty ins Leben rufen, zu der niemand richtig erscheint?",
  "Wer würde eher auf einer Party versuchen, alle Anwesenden zu einem Gruppenspiel zu überreden?",
  "Wer würde eher bei einem Geburtstag die Rede halten, ohne sich vorbereitet zu haben?",
  "Wer würde eher versuchen, mit einer schlechten Ausrede eine langweilige Party frühzeitig zu verlassen?",
  "Wer würde eher auf einer Feier das Buffet komplett leer essen, bevor die Gäste kommen?",
  "Wer würde eher bei einem Escape-Game-Abend die Gruppe anführen?",
  "Wer würde eher versuchen, bei einer Silvesterparty den Mitternachtskuss zu verpassen?",
  "Wer würde eher auf einer WG-Party als Gastgeber oder Gastgeberin komplett den Überblick verlieren?",
  "Wer würde eher bei einem Spieleabend so ehrgeizig werden, dass die Stimmung kippt?",
  "Wer würde eher versuchen, eine Flashmob-Aktion auf einer Feier zu starten?",
  "Wer würde eher bei einer Party den DJ spielen, obwohl er/sie noch nie aufgelegt hat?",
  "Wer würde eher versuchen, eine spontane Nachtwanderung mit der ganzen Gruppe zu organisieren?",
  "Wer würde eher auf einer Feier ein Trinkspiel erfinden, das sofort zum Klassiker wird?",
  "Wer würde eher bei einem Bowlingabend am Ende die schlechteste Punktzahl haben?",
  "Wer würde eher versuchen, alle Gäste einer Party in ein Gruppenfoto zu bekommen?",
  "Wer würde eher bei einer Feier als Erste/r ein Spontan-Feuerwerk an Komplimenten verteilen?",
  "Wer würde eher versuchen, eine Party bis in den Morgen zu retten, wenn die Stimmung sinkt?",
  "Wer würde eher von einem Zehn-Meter-Turm springen, ohne lange nachzudenken?",
  "Wer würde eher sich freiwillig für ein Bungee-Jumping-Experiment melden?",
  "Wer würde eher als Erste/r eine Achterbahn mit dem höchsten Nervenkitzel ausprobieren?",
  "Wer würde eher mit Haien tauchen gehen, obwohl er/sie Angst vor dem Meer hat?",
  "Wer würde eher freiwillig einer spinnenartigen Kreatur nahekommen, um Fotos zu machen?",
  "Wer würde eher bei einer Mutprobe als Letzte/r aufgeben?",
  "Wer würde eher mitten in der Nacht allein durch einen dunklen Wald gehen?",
  "Wer würde eher freiwillig auf der Bühne vor Hunderten Fremden sprechen?",
  "Wer würde eher sich für einen Fallschirmsprung im Tandem anmelden, ohne es lange zu überlegen?",
  "Wer würde eher freiwillig eine extrem scharfe Chilischote probieren?",
  "Wer würde eher versuchen, eine Klippe hinunterzuklettern, ohne Erfahrung damit zu haben?",
  "Wer würde eher sich freiwillig für ein Eisbaden im Winter melden?",
  "Wer würde eher als Erste/r eine Geisterbahn durchstehen, ohne die Augen zu schließen?",
  "Wer würde eher versuchen, einen Vortrag komplett ohne Vorbereitung zu halten?",
  "Wer würde eher freiwillig auf einem Motorrad Beifahrer oder Beifahrerin bei Höchstgeschwindigkeit sein?",
  "Wer würde eher sich trauen, einen Fremden nach seiner Telefonnummer für einen Freund zu fragen?",
  "Wer würde eher freiwillig eine kalte Dusche als Mutprobe nehmen?",
  "Wer würde eher versuchen, im Dunkeln allein zelten zu gehen?",
  "Wer würde eher sich trauen, auf offener Bühne spontan zu improvisieren?",
  "Wer würde eher freiwillig von einer Klippe ins Wasser springen?",
  "Wer würde eher sich trauen, einem Fremden ein ehrliches Kompliment zu machen?",
  "Wer würde eher versuchen, mit verbundenen Augen ein Gericht zu probieren, ohne zu wissen, was es ist?",
  "Wer würde eher freiwillig auf einer Zip-Line über eine Schlucht fliegen?",
  "Wer würde eher sich trauen, eine Rede ohne Karteikarten zu halten?",
  "Wer würde eher versuchen, eine Nacht allein auf einem Berggipfel zu verbringen?",
  "Wer würde eher freiwillig als Erste/r eine neue Extremsportart ausprobieren?",
  "Wer würde eher sich trauen, mitten im Winter im See zu schwimmen?",
  "Wer würde eher freiwillig einen Sprung von einem Felsen ins kalte Wasser wagen?",
  "Wer würde eher sich trauen, spontan bei einem Casting mitzumachen?",
  "Wer würde eher versuchen, eine Höhle ohne Taschenlampe zu erkunden?",
  "Wer würde eher freiwillig als Testperson für ein neues, unbekanntes Fahrgeschäft dienen?",
  "Wer würde eher sich trauen, öffentlich eine peinliche Geschichte über sich selbst zu erzählen?",
  "Wer würde eher versuchen, eine wilde Achterbahnfahrt mit erhobenen Händen durchzustehen?",
  "Wer würde eher freiwillig ein Fallschirmspringen ohne vorheriges Training wagen?",
  "Wer würde eher sich trauen, mitten in der Stadt einen spontanen Tanz aufzuführen?",
  "Wer würde eher beim Kochen versehentlich die Küche in Brand setzen?",
  "Wer würde eher ein Regal beim Möbelaufbau falsch zusammenbauen und es erst später merken?",
  "Wer würde eher beim Tragen von Umzugskartons alles fallen lassen?",
  "Wer würde eher versuchen, ein Bild aufzuhängen, und dabei die ganze Wand demolieren?",
  "Wer würde eher beim Backen versehentlich Salz statt Zucker verwenden?",
  "Wer würde eher beim Autofahren den Rückwärtsgang mit dem ersten Gang verwechseln?",
  "Wer würde eher versuchen, einen Reifen zu wechseln, und dabei komplett scheitern?",
  "Wer würde eher beim Aufräumen mehr Chaos anrichten, als vorher da war?",
  "Wer würde eher versehentlich die Waschmaschine mit einem roten Socken überfluten und alles rosa färben?",
  "Wer würde eher beim Grillen die Kohle nicht angezündet bekommen?",
  "Wer würde eher versuchen, ein Regal zu montieren, ohne die Anleitung zu lesen?",
  "Wer würde eher beim Zelten das Zelt mitten in der Nacht zusammenbrechen lassen?",
  "Wer würde eher versehentlich einen Wasserhahn kaputt machen und die ganze Küche fluten?",
  "Wer würde eher beim Rasenmähen aus Versehen die Blumenbeete plattmachen?",
  "Wer würde eher versuchen, ein Fahrrad zu reparieren, und es danach kaputter zurücklassen?",
  "Wer würde eher beim Einparken mehrmals gegen den Bordstein fahren?",
  "Wer würde eher versehentlich eine ganze Kiste Eier fallen lassen?",
  "Wer würde eher beim Streichen einer Wand mehr Farbe auf sich selbst als auf die Wand bekommen?",
  "Wer würde eher versuchen, einen Kuchen zu backen, der komplett zusammenfällt?",
  "Wer würde eher beim Aufhängen von Weihnachtsdeko die ganze Lichterkette verheddern?",
  "Wer würde eher versehentlich das Auto mit dem falschen Kraftstoff betanken?",
  "Wer würde eher beim Zusammenbauen von Möbeln am Ende Schrauben übrighaben?",
  "Wer würde eher beim Wandern die eigenen Schnürsenkel ständig lösen und darüber stolpern?",
  "Wer würde eher versuchen, einen Nagel einzuschlagen, und stattdessen auf den Daumen treffen?",
  "Wer würde eher beim Renovieren aus Versehen die falsche Wand streichen?",
  "Wer würde eher versuchen, eine Glühbirne zu wechseln, und dabei die Sicherung rausfliegen lassen?",
  "Wer würde eher beim Spülen ein Glas nach dem anderen zerbrechen?",
  "Wer würde eher versehentlich den Gartenschlauch ins offene Fenster statt auf die Pflanzen richten?",
  "Wer würde eher beim Kofferpacken alles Wichtige vergessen, aber unnötigen Kram mitnehmen?",
  "Wer würde eher versuchen, ein Regal ohne übrige Teile aufzubauen und trotzdem scheitern?",
  "Wer würde eher beim Anzünden von Kerzen aus Versehen eine Tischdecke ansengen?",
  "Wer würde eher versuchen, einen Drucker anzuschließen, und dabei komplett verzweifeln?",
  "Wer würde eher beim Wäscheaufhängen die Hälfte der Wäscheklammern verlieren?",
  "Wer würde eher versehentlich beim Duschen das ganze Badezimmer unter Wasser setzen?",
  "Wer würde eher versuchen, ein Zelt bei Sturm aufzubauen, und komplett scheitern?",
  "Wer würde eher stundenlang durch Social Media scrollen, ohne es zu merken?",
  "Wer würde eher aus Versehen ein peinliches altes Foto posten?",
  "Wer würde eher ein Update installieren und danach das Handy komplett neu einrichten müssen?",
  "Wer würde eher versehentlich einem Ex oder einer Ex ein Like unter einem alten Foto dalassen?",
  "Wer würde eher versuchen, mit einem KI-Chatbot stundenlang zu plaudern, statt zu arbeiten?",
  "Wer würde eher ein virales Video drehen, ohne es zu beabsichtigen?",
  "Wer würde eher das eigene Passwort so oft vergessen, dass er/sie ständig ein neues anfordern muss?",
  "Wer würde eher versuchen, ein Handyspiel bis spät in die Nacht durchzuspielen?",
  "Wer würde eher versehentlich in einer Gruppen-Chat-Nachricht etwas Peinliches über jemanden schreiben?",
  "Wer würde eher ohne Internetverbindung völlig hilflos sein?",
  "Wer würde eher einen kompletten Tag ohne jedes Bildschirmgerät überstehen?",
  "Wer würde eher versuchen, mit einer Smartwatch jede Bewegung zu tracken?",
  "Wer würde eher versehentlich eine private Story für alle statt nur für enge Freunde posten?",
  "Wer würde eher als Erste/r eine neue App ausprobieren, bevor sie alle kennen?",
  "Wer würde eher ein Handy fallen lassen und den Bildschirm zersplittern?",
  "Wer würde eher versuchen, mit einem Streaming-Kanal berühmt zu werden?",
  "Wer würde eher aus Versehen einen wichtigen Ordner löschen, ohne ein Backup zu haben?",
  "Wer würde eher versuchen, ein virales Rezept nachzukochen und es komplett vermasseln?",
  "Wer würde eher stundenlang in einem Videocall vergessen, dass die Kamera an ist?",
  "Wer würde eher versuchen, einen Social-Media-Trend nachzumachen und dabei scheitern?",
  "Wer würde eher die eigene Bildschirmzeit-Statistik verstecken, weil sie zu hoch ist?",
  "Wer würde eher aus Versehen im Onlineshop viel zu viel bestellen?",
  "Wer würde eher versuchen, einen alten Computer zu reparieren, statt einen neuen zu kaufen?",
  "Wer würde eher ein Selfie so oft wiederholen, bis es perfekt ist?",
  "Wer würde eher versehentlich Kommentare unter dem falschen Account posten?",
  "Wer würde eher versuchen, mit einem Fitness-Tracker jeden einzelnen Schritt zu zählen?",
  "Wer würde eher ein Handyupdate ewig hinauszögern, aus Angst, etwas geht kaputt?",
  "Wer würde eher versuchen, einen kompletten Serienmarathon an einem Wochenende durchzuziehen?",
  "Wer würde eher versehentlich eine falsche Nummer anrufen und trotzdem ein langes Gespräch führen?",
  "Wer würde eher ein WLAN-Passwort vergessen und stundenlang danach suchen?",
  "Wer würde eher versuchen, ein Meme zu erstellen, das tatsächlich viral geht?",
  "Wer würde eher beim Onlineshopping aus Versehen die falsche Größe bestellen?",
  "Wer würde eher versehentlich ein privates Foto im falschen Chat teilen?",
  "Wer würde eher stundenlang nach dem perfekten Filter für ein Foto suchen?",
  "Wer würde eher versuchen, ein technisches Problem selbst zu lösen, statt den Support anzurufen?",
  "Wer würde eher ein ganzes Glas Chilisoße aus Mutprobe trinken?",
  "Wer würde eher versuchen, ein riesiges Steak in einem Wettessen zu gewinnen?",
  "Wer würde eher freiwillig ein exotisches Gericht probieren, ohne zu wissen, was drin ist?",
  "Wer würde eher versuchen, ein komplett neues Rezept ohne Kochbuch zu erfinden?",
  "Wer würde eher beim Kochen alle Zutaten verwechseln und trotzdem etwas Essbares zaubern?",
  "Wer würde eher einen ganzen Kuchen allein essen?",
  "Wer würde eher versuchen, mit Stäbchen ein Gericht zu essen, das eigentlich einen Löffel braucht?",
  "Wer würde eher freiwillig einen Tag lang nur von Fastfood leben?",
  "Wer würde eher versuchen, ein veganes Gericht so nachzukochen, dass niemand den Unterschied merkt?",
  "Wer würde eher bei einem Kochwettbewerb völlig überfordert sein?",
  "Wer würde eher versuchen, ein Gericht mit den seltsamsten Zutatenkombinationen zu kreieren?",
  "Wer würde eher freiwillig eine Runde Austern probieren, obwohl er/sie skeptisch ist?",
  "Wer würde eher versuchen, ein perfektes Spiegelei zu braten, und es dabei anbrennen lassen?",
  "Wer würde eher einen ganzen Abend nur süße Sachen essen?",
  "Wer würde eher versuchen, ein Rezept aus dem Internet nachzukochen, ohne die Mengenangaben zu beachten?",
  "Wer würde eher freiwillig scharfe Wings bis zur höchsten Schärfestufe durchprobieren?",
  "Wer würde eher versuchen, eine Diät für genau einen Tag durchzuhalten?",
  "Wer würde eher bei einem Buffet als Erste/r zugreifen?",
  "Wer würde eher versuchen, ein Gericht ganz ohne Rezept nachzukochen, nur aus der Erinnerung?",
  "Wer würde eher freiwillig einen ganzen Abend Sushi selbst rollen, statt es zu bestellen?",
  "Wer würde eher versuchen, mit Freunden ein Grillfest zu organisieren, das komplett aus dem Ruder läuft?",
  "Wer würde eher eine ganze Tüte Chips allein leeren, während er/sie einen Film schaut?",
  "Wer würde eher versuchen, ein Gericht komplett ohne Salz zu würzen und es trotzdem gut hinzubekommen?",
  "Wer würde eher freiwillig als Erste/r ein neues, ungewöhnliches Getränk probieren?",
  "Wer würde eher versuchen, einen ganzen Kaffee ohne Zucker zu trinken, obwohl er/sie es hasst?",
  "Wer würde eher bei einem Grillabend das Fleisch komplett verbrennen?",
  "Wer würde eher versuchen, ein Drei-Gänge-Menü für Freunde zu kochen, ohne je zuvor gekocht zu haben?",
  "Wer würde eher freiwillig eine Currywurst mit extra scharfer Soße bestellen?",
  "Wer würde eher versuchen, morgens als Erstes einen Smoothie mit Gemüse statt Obst zu trinken?",
  "Wer würde eher bei einer Weinprobe so tun, als würde er/sie sich auskennen?",
  "Wer würde eher versuchen, ein komplettes Festmahl für die Familie allein zu kochen?",
  "Wer würde eher freiwillig ein ganzes Glas scharfen Essig aus Mutprobe trinken?",
  "Wer würde eher versuchen, ein Eis zu essen, bevor es komplett schmilzt, und trotzdem scheitern?",
  "Wer würde eher bei einem Picknick vergessen, das Wichtigste einzupacken?",
  "Wer würde eher versuchen, mitten in der Nacht ein komplettes Frühstück zu kochen, weil er/sie Heißhunger hat?",
  "Wer würde eher versehentlich in einer Nachrichtensendung im Hintergrund zu sehen sein und dadurch berühmt werden?",
  "Wer würde eher als Statist oder Statistin in einem Film entdeckt werden?",
  "Wer würde eher ein Autogramm von einem Fremden verlangt bekommen, obwohl er/sie niemand Bekanntes ist?",
  "Wer würde eher versuchen, bei einer Fernsehshow vorzusprechen?",
  "Wer würde eher aus Versehen zur Symbolfigur eines Internet-Trends werden?",
  "Wer würde eher versuchen, eine eigene Talkshow zu moderieren?",
  "Wer würde eher bei einer Straßenumfrage die witzigste Antwort geben, die dann im Fernsehen läuft?",
  "Wer würde eher versehentlich in einem viralen Video die Hauptrolle spielen?",
  "Wer würde eher versuchen, ein eigenes Buch zu schreiben und damit berühmt zu werden?",
  "Wer würde eher bei einer Preisverleihung aus Versehen auf die Bühne gerufen werden?",
  "Wer würde eher als Double für eine berühmte Person durchgehen?",
  "Wer würde eher versuchen, bei einem Radiosender live on air anzurufen?",
  "Wer würde eher aus Versehen in einer Werbung zu sehen sein?",
  "Wer würde eher bei einem Interview auf der Straße die klügste Antwort geben?",
  "Wer würde eher versuchen, mit einem eigenen Podcast Erfolg zu haben?",
  "Wer würde eher als Erste/r für ein Cover-Foto angefragt werden?",
  "Wer würde eher versehentlich zur Berühmtheit in der eigenen Nachbarschaft werden?",
  "Wer würde eher versuchen, bei einem Casting für eine Reality-Show mitzumachen?",
  "Wer würde eher aus Versehen bei einer Liveübertragung im Hintergrund komische Sachen machen?",
  "Wer würde eher versuchen, eine eigene Modelinie zu entwerfen?",
  "Wer würde eher bei einer Pressekonferenz die unbequemste Frage stellen?",
  "Wer würde eher versehentlich zum Trending-Thema werden, ohne es zu wollen?",
  "Wer würde eher versuchen, ein eigenes Lied zu schreiben und zu veröffentlichen?",
  "Wer würde eher als Erste/r für ein Interview in der Lokalzeitung angefragt?",
  "Wer würde eher versuchen, mit einer verrückten Erfindung in die Nachrichten zu kommen?",
  "Wer würde eher bei einem Flashmob mitten in der Stadt mitmachen?",
  "Wer würde eher versehentlich das Gesicht einer viralen Werbekampagne werden?",
  "Wer würde eher versuchen, ein eigenes Comedy-Programm auf die Bühne zu bringen?",
  "Wer würde eher als Erste/r bei einer Fernsehshow als Kandidat oder Kandidatin ausgewählt?",
  "Wer würde eher versuchen, mit einem verrückten Talent bei einer Castingshow zu überzeugen?",
  "Wer würde eher aus Versehen bei einer Sportübertragung ins Bild laufen und berühmt werden?",
  "Wer würde eher versuchen, eine eigene Kunstausstellung zu organisieren?",
  "Wer würde eher als Gesicht einer wohltätigen Kampagne ausgewählt werden?",
  "Wer würde eher versuchen, eine originelle Geschäftsidee im Fernsehen vorzustellen?",
  "Wer würde eher versehentlich zum Gesicht eines Internet-Memes werden?",
  "Wer würde eher eine Hausaufgabe in letzter Minute vor der Schule fertigmachen?",
  "Wer würde eher bei einer Prüfung komplett das Zeitgefühl verlieren?",
  "Wer würde eher eine ganze Nacht durchlernen, statt rechtzeitig anzufangen?",
  "Wer würde eher in der Schule ständig zu spät kommen?",
  "Wer würde eher versuchen, einer Lehrkraft eine kreative Ausrede für fehlende Hausaufgaben zu liefern?",
  "Wer würde eher bei einer Gruppenarbeit am Ende die meiste Arbeit übernehmen?",
  "Wer würde eher versehentlich in der falschen Vorlesung sitzen und es erst nach der Hälfte merken?",
  "Wer würde eher bei einem Referat komplett den Faden verlieren?",
  "Wer würde eher versuchen, ein komplettes Semester nur mit Karteikarten zu bestehen?",
  "Wer würde eher in der Bibliothek versehentlich einschlafen?",
  "Wer würde eher versuchen, eine Prüfung mit reinem Bauchgefühl zu bestehen?",
  "Wer würde eher bei einer Klassenfahrt für die meiste Aufregung sorgen?",
  "Wer würde eher versehentlich das falsche Fach für eine Prüfung lernen?",
  "Wer würde eher als Klassensprecher oder Klassensprecherin kandidieren, ohne wirklich vorbereitet zu sein?",
  "Wer würde eher bei einer mündlichen Prüfung komplett dicht machen?",
  "Wer würde eher versuchen, eine Seminararbeit erst am Abgabetag anzufangen?",
  "Wer würde eher in der Schule beim Schummeln erwischt werden, obwohl er/sie es gar nicht vorhatte?",
  "Wer würde eher versuchen, sich freiwillig für ein Referat vor der ganzen Klasse zu melden?",
  "Wer würde eher bei einer Klausur die falsche Antwort mit voller Überzeugung aufschreiben?",
  "Wer würde eher versuchen, während einer Vorlesung heimlich etwas anderes zu erledigen?",
  "Wer würde eher als Erste/r einen Studienplatz im Ausland ergattern?",
  "Wer würde eher versuchen, eine komplette Prüfungsphase nur mit Kaffee zu überstehen?",
  "Wer würde eher bei einer Abschlussfeier die Rede halten?",
  "Wer würde eher versuchen, ein Fach zu wählen, nur weil ein Freund oder eine Freundin es auch wählt?",
  "Wer würde eher versehentlich zur falschen Uhrzeit zu einer Prüfung erscheinen?",
  "Wer würde eher versuchen, in einer Gruppenarbeit als Vermittler oder Vermittlerin zwischen Streithähnen zu agieren?",
  "Wer würde eher bei einem Vortrag die Technik zum Absturz bringen?",
  "Wer würde eher versuchen, ein komplettes Studium neben einem Vollzeitjob durchzuziehen?",
  "Wer würde eher versehentlich das falsche Buch zur Prüfung mitbringen?",
  "Wer würde eher als Letzte/r im Kurs die Prüfung abgeben?",
  "Wer würde eher versuchen, sich für ein Auslandssemester zu bewerben, ohne die Sprache zu können?",
  "Wer würde eher bei einer Klassenfahrt das Zimmer komplett auf den Kopf stellen?",
  "Wer würde eher versuchen, eine Abschlussarbeit über ein völlig ungewöhnliches Thema zu schreiben?",
  "Wer würde eher in einer Prüfung aus Nervosität den eigenen Namen vergessen?",
  "Wer würde eher versuchen, mit den letzten Ersparnissen noch schnell ein Zusatzstudium zu finanzieren?",
  "Wer würde eher versuchen, einem streunenden Tier ein Zuhause zu geben?",
  "Wer würde eher ein Haustier menschlicher behandeln als die meisten Menschen?",
  "Wer würde eher versuchen, einem Papagei Schimpfwörter beizubringen?",
  "Wer würde eher aus Versehen ein exotisches Tier als Haustier adoptieren?",
  "Wer würde eher versuchen, mit einem Hund ein komplettes Gespräch zu führen?",
  "Wer würde eher bei einem Tierheim-Besuch am Ende mit mehr Tieren nach Hause gehen, als geplant war?",
  "Wer würde eher versuchen, einer Katze Kunststücke beizubringen?",
  "Wer würde eher ein Haustier mit auf eine Weltreise nehmen wollen?",
  "Wer würde eher versuchen, ein Aquarium mit den ausgefallensten Fischen einzurichten?",
  "Wer würde eher einem wilden Eichhörnchen im Park Futter aus der Hand geben?",
  "Wer würde eher versuchen, ein verletztes Tier auf der Straße zu retten und selbst zu pflegen?",
  "Wer würde eher ein Haustier nach einem berühmten Filmcharakter benennen?",
  "Wer würde eher versuchen, mit einem Pferd eine enge Bindung aufzubauen?",
  "Wer würde eher aus Versehen zu viele Haustiere gleichzeitig besitzen?",
  "Wer würde eher versuchen, einem Hund beizubringen, das Handy zu apportieren?",
  "Wer würde eher bei einem Zoobesuch am längsten vor einem einzigen Gehege stehen bleiben?",
  "Wer würde eher versuchen, mit Bienen zu imkern, obwohl er/sie Angst vor Stichen hat?",
  "Wer würde eher ein Haustier heimlich mit ins Bett nehmen, obwohl es verboten ist?",
  "Wer würde eher versuchen, einem Pony das Zähneputzen beizubringen?",
  "Wer würde eher aus Versehen ein Insekt als Haustier behalten?",
  "Wer würde eher versuchen, ein Haustier für einen viralen Videoclip zu trainieren?",
  "Wer würde eher bei einem Ausritt vom Pferd fallen und trotzdem weiterreiten wollen?",
  "Wer würde eher versuchen, mit einem Schaf auf einer Wiese Freundschaft zu schließen?",
  "Wer würde eher ein Haustierkostüm für ein Fest nähen?",
  "Wer würde eher versuchen, einem Wellensittich das Pfeifen einer Melodie beizubringen?",
  "Wer würde eher bei einem Bauernhofurlaub sofort ein Lieblingstier finden?",
  "Wer würde eher versuchen, ein verlorenes Haustier tagelang in der ganzen Stadt zu suchen?",
  "Wer würde eher aus Versehen ein wildes Tier für ein zahmes halten und es streicheln wollen?",
  "Wer würde eher versuchen, mit einem Frettchen als Haustier klarzukommen?",
  "Wer würde eher bei einem Reiterhof-Besuch am Ende einen eigenen Reitkurs buchen?",
  "Wer würde eher versuchen, einer Schildkröte das Rennen beizubringen?",
  "Wer würde eher aus Versehen einem fremden Hund im Park den ganzen Nachmittag hinterherlaufen?",
  "Wer würde eher versuchen, ein Haustierhotel für den eigenen Hund zu eröffnen?",
  "Wer würde eher bei einem Tierfilm mehr weinen als bei einem Liebesfilm?",
  "Wer würde eher versuchen, mit einem Alpaka spazieren zu gehen?",
  "Wer würde eher den ganzen Urlaub am Strand verschlafen?",
  "Wer würde eher versuchen, im Urlaub jeden Tag ein neues Ausflugsziel zu finden?",
  "Wer würde eher im Urlaub den kompletten Koffer falsch packen?",
  "Wer würde eher versuchen, im Urlaub die Landessprache innerhalb weniger Tage zu lernen?",
  "Wer würde eher im Hotel versehentlich das falsche Zimmer betreten?",
  "Wer würde eher versuchen, im Urlaub jeden Sonnenuntergang zu fotografieren?",
  "Wer würde eher im Urlaub das Rückflugdatum verwechseln?",
  "Wer würde eher versuchen, im Urlaub ein Souvenir für jede einzelne Person zu Hause zu kaufen?",
  "Wer würde eher im Urlaub einen kompletten Tag im Spa verbringen, statt die Stadt zu erkunden?",
  "Wer würde eher versuchen, im Urlaub eine lokale Kochklasse zu besuchen?",
  "Wer würde eher im Urlaub den Sonnenbrand des Jahres bekommen?",
  "Wer würde eher versuchen, im Urlaub jeden Tag am Pool zu verbringen, statt etwas zu unternehmen?",
  "Wer würde eher im Urlaub das Hotelzimmer mit dem schlechtesten Ausblick bekommen?",
  "Wer würde eher versuchen, im Urlaub eine lokale Sportart auszuprobieren?",
  "Wer würde eher im Urlaub die Reisetasche am Flughafen vergessen?",
  "Wer würde eher versuchen, im Urlaub ein authentisches lokales Fest zu besuchen?",
  "Wer würde eher im Urlaub versehentlich am Strand einschlafen und dabei komplett verbrennen?",
  "Wer würde eher versuchen, im Urlaub jeden Tag ein anderes Restaurant auszuprobieren?",
  "Wer würde eher im Urlaub den Reisepass kurz vor dem Abflug verlegen?",
  "Wer würde eher versuchen, im Urlaub eine ganze Insel an einem Tag zu erkunden?",
  "Wer würde eher im Urlaub am Ende mehr Zeit im Hotelzimmer als draußen verbringen?",
  "Wer würde eher versuchen, im Urlaub mit Einheimischen ins Gespräch zu kommen?",
  "Wer würde eher im Urlaub eine ganze Woche ohne festen Plan verbringen?",
  "Wer würde eher versuchen, im Urlaub ein Andenken zu finden, das niemand sonst hat?",
  "Wer würde eher im Urlaub das Auto der Mietwagenfirma verkratzen?",
  "Wer würde eher versuchen, im Urlaub jeden Tag früh aufzustehen, um nichts zu verpassen?",
  "Wer würde eher im Urlaub versehentlich in einer Touristenfalle landen?",
  "Wer würde eher versuchen, im Urlaub eine ganze Bucket List abzuarbeiten?",
  "Wer würde eher im Urlaub die Kamera zu Hause vergessen?",
  "Wer würde eher versuchen, im Urlaub den Zimmerservice jeden Tag zu bestellen?",
  "Wer würde eher im Urlaub eine Wanderung unterschätzen und komplett erschöpft ankommen?",
  "Wer würde eher versuchen, im Urlaub ein Tattoo als Andenken zu holen?",
  "Wer würde eher im Urlaub die Zeitverschiebung komplett unterschätzen?",
  "Wer würde eher versuchen, im Urlaub jeden Tag ein neues Wassersportabenteuer auszuprobieren?",
  "Wer würde eher im Urlaub eine Nachricht in einer Flasche ins Meer werfen?",
  "Wer würde eher bei einem Marathon schon nach der Hälfte aufgeben wollen?",
  "Wer würde eher versuchen, eine neue Sportart zu lernen und sofort damit aufhören?",
  "Wer würde eher bei einem Fußballspiel als Erste/r ein Tor schießen?",
  "Wer würde eher versuchen, sich für einen Triathlon anzumelden, ohne wirklich trainiert zu haben?",
  "Wer würde eher bei einem Wettkampf aus reinem Ehrgeiz übertreiben?",
  "Wer würde eher versuchen, im Fitnessstudio die schwersten Gewichte zu heben, ohne die Technik zu kennen?",
  "Wer würde eher bei einem Freizeitspiel zu wettkampfmäßig werden?",
  "Wer würde eher versuchen, eine komplette Yoga-Stunde durchzuhalten, ohne umzufallen?",
  "Wer würde eher bei einem Tanzkurs die kompliziertesten Schritte sofort draufhaben?",
  "Wer würde eher versuchen, mit dem Klettern anzufangen, obwohl er/sie Höhenangst hat?",
  "Wer würde eher bei einem Fahrradrennen als Erste/r schlappmachen?",
  "Wer würde eher versuchen, sich für einen Ironman anzumelden, aus purer Neugier?",
  "Wer würde eher bei einem Volleyballspiel den entscheidenden Punkt verschlagen?",
  "Wer würde eher versuchen, Skifahren zu lernen und dabei ständig hinfallen?",
  "Wer würde eher bei einem Basketballspiel den Ball versehentlich ins falsche Netz werfen?",
  "Wer würde eher versuchen, eine Runde Boxen auszuprobieren, ohne je geboxt zu haben?",
  "Wer würde eher bei einem Schwimmwettkampf die Bahn wechseln, weil er/sie sich verschwimmt?",
  "Wer würde eher versuchen, sich für einen Hindernislauf anzumelden, weil es lustig klingt?",
  "Wer würde eher bei einem Tennisspiel öfter den Ball verfehlen als treffen?",
  "Wer würde eher versuchen, im Fitnessstudio Neujahrsvorsätze wirklich durchzuhalten?",
  "Wer würde eher bei einem Golfturnier den Ball ins Wasser schlagen?",
  "Wer würde eher versuchen, eine Klettertour ohne vorheriges Training zu meistern?",
  "Wer würde eher bei einem Sportfest in der eigenen Nachbarschaft als Erste/r antreten?",
  "Wer würde eher versuchen, sich für einen Bergmarathon anzumelden, ohne die Höhenmeter zu bedenken?",
  "Wer würde eher bei einem Beachvolleyball-Turnier im Sand hängen bleiben?",
  "Wer würde eher versuchen, eine ganze Saison lang jede Woche eine neue Sportart auszuprobieren?",
  "Wer würde eher bei einem Wettrennen im letzten Moment noch überholen?",
  "Wer würde eher versuchen, Surfen zu lernen und dabei ständig ins Wasser fallen?",
  "Wer würde eher bei einem Dartturnier versehentlich die Scheibe komplett verfehlen?",
  "Wer würde eher versuchen, sich für ein Ruderteam anzumelden, ohne je gerudert zu haben?",
  "Wer würde eher bei einem Kegelabend die meisten Pins auf einmal treffen?",
  "Wer würde eher versuchen, eine Runde Bogenschießen auszuprobieren und dabei überraschend gut sein?",
  "Wer würde eher bei einer Wanderung zum Gipfel als Erste/r ankommen?",
  "Wer würde eher versuchen, sich für einen Firmenlauf anzumelden, obwohl er/sie ungeübt ist?",
  "Wer würde eher bei einem Eishockeyspiel als Erste/r auf dem Eis ausrutschen?",
  "Wer würde eher, wenn er/sie unsichtbar wäre, den ganzen Tag Streiche spielen?",
  "Wer würde eher, wenn er/sie fliegen könnte, sofort um die Welt reisen?",
  "Wer würde eher, wenn er/sie eine Fähigkeit wählen müsste, Gedanken lesen können wollen?",
  "Wer würde eher, wenn er/sie einen Tag lang ein Tier sein könnte, ein Adler sein wollen?",
  "Wer würde eher, wenn er/sie einen Wunsch frei hätte, ihn für andere statt für sich selbst nutzen?",
  "Wer würde eher, wenn er/sie die Zeit zurückdrehen könnte, sofort in die Kindheit zurückwollen?",
  "Wer würde eher, wenn er/sie ein Superheld oder eine Superheldin wäre, das schlechteste Kostüm tragen?",
  "Wer würde eher, wenn er/sie einen Tag lang berühmt wäre, es komplett genießen?",
  "Wer würde eher, wenn er/sie im Lotto gewinnen würde, es sofort allen erzählen?",
  "Wer würde eher, wenn er/sie eine Zeitmaschine hätte, in die Zukunft statt in die Vergangenheit reisen?",
  "Wer würde eher, wenn er/sie einen Tag lang die Kontrolle über das Wetter hätte, für ewigen Sonnenschein sorgen?",
  "Wer würde eher, wenn er/sie eine geheime Doppelidentität hätte, sie niemandem verraten?",
  "Wer würde eher, wenn er/sie ein Buch über sein oder ihr Leben schreiben müsste, es zu einer Komödie machen?",
  "Wer würde eher, wenn er/sie einen Tag im Weltall verbringen könnte, sofort Ja sagen?",
  "Wer würde eher, wenn er/sie eine Sprache sofort perfekt lernen könnte, eine völlig exotische wählen?",
  "Wer würde eher, wenn er/sie einen Tag als Roboter leben müsste, es lustig finden?",
  "Wer würde eher, wenn er/sie sich in eine Berühmtheit verwandeln könnte, es niemandem sagen?",
  "Wer würde eher, wenn er/sie ein magisches Haustier haben könnte, einen Drachen wählen?",
  "Wer würde eher, wenn er/sie eine Insel besitzen würde, dort eine riesige Party veranstalten?",
  "Wer würde eher, wenn er/sie einen Tag lang alles wissen könnte, sofort Weltprobleme lösen wollen?",
  "Wer würde eher, wenn er/sie sich teleportieren könnte, ständig zu spät kommen, weil er/sie es vergisst zu nutzen?",
  "Wer würde eher, wenn er/sie ein Königreich regieren müsste, es chaotisch, aber fair führen?",
  "Wer würde eher, wenn er/sie für einen Tag jung wieder sein könnte, den ganzen Tag draußen spielen?",
  "Wer würde eher, wenn er/sie eine Schatzkarte finden würde, sofort auf Schatzsuche gehen?",
  "Wer würde eher, wenn er/sie eine Zauberformel hätte, sie für einen riesigen Streich nutzen?",
  "Wer würde eher, wenn er/sie ein Musikinstrument aus dem Nichts spielen könnte, ein Konzert geben?",
  "Wer würde eher, wenn er/sie einen Tag lang unbegrenzt Geld hätte, es komplett verschenken?",
  "Wer würde eher, wenn er/sie in einem Videospiel leben müsste, ein Open-World-Abenteuer wählen?",
  "Wer würde eher, wenn er/sie mit Tieren sprechen könnte, den ganzen Tag mit ihnen plaudern?",
  "Wer würde eher, wenn er/sie ein Piratenschiff kapern müsste, als Kapitän oder Kapitänin führen?",
  "Wer würde eher, wenn er/sie einen Tag lang riesig wäre, eine ganze Stadt erkunden?",
  "Wer würde eher, wenn er/sie in eine Fantasiewelt versetzt würde, sofort ein Abenteuer beginnen?",
  "Wer würde eher, wenn er/sie den perfekten Tag planen dürfte, ihn komplett allein verbringen?",
  "Wer würde eher, wenn er/sie ein Orakel befragen könnte, nur nach der Zukunft fragen?",
  "Wer würde eher, wenn er/sie eine unsichtbare Superkraft hätte, sie für gute Zwecke einsetzen?",
];

export function pickQuestion(exclude: Set<string> = new Set()): string {
  let pool = QUESTIONS.filter((q) => !exclude.has(q));
  if (pool.length === 0) {
    // Whole pool used up — start a fresh no-repeat cycle instead of falling
    // back to picking from the unfiltered list forever.
    exclude.clear();
    pool = QUESTIONS;
  }
  return pool[Math.floor(Math.random() * pool.length)];
}
